### ISSUE TITLE
Datepicker not localized

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#388] opened 2016-01-11 10:37 UTC
Datepicker use default English culture information.

**Comment by rhukster** [comment] 2016-01-15 00:46
Yah, this is not super trivial because we currently use a 3rd party date picker.  To localize it would mean either major refactoring of that 3rd party picker, or we do our own.  

The second choice is probably the smarter option going forward but will take some time.

**Comment by nineteeneightyeight** [comment] 2016-02-10 16:09
Apologies if I'm misunderstanding the issue, but it seems related. When using the datepicker it's using the 'Page Date Format' from your config. This would be all well and good, but by default (auto guess) it uses my UK date format, which when saved into the markdown appears `dd-mm-yyyy 00:00:00`. This means that the date can not be ordered against, because it's expecting `strtotime` format. The only way to get around this is to force the datepicker to output as `yyyy-mm-dd 00:00:00` by changing the 'Page Date Format'.

**Comment by rhukster** [comment] 2016-02-10 16:24
@w00fz is actually in the process of revamping the date/time picker, so perhaps he can look and test this with the new code.

**Comment by w00fz** [comment] 2016-02-10 20:29
To make sure I understood right. If you have your Date field set to `10-02-2016` (10 Feb 2016) and your format is `d-m-Y`, when you go to change the format to something else, ie `m-d-Y`, you expect the Date picker to correct to `02-10-2016`?

If that's the case then yes, this is already working in the new `es6_revamp` branch but you need to keep in mind a few things here. 

The datepicker is just an utility tool to ease the job of having to manually write a date/time. It knows what format you set in the system config and uses that to format the date you pick. Once the page is saved, that's the end of the datepicker job.
This means that if you change the format after the facts, your page `date` field is still as it was before, unless you fix the date in the page and save again.

If you are trying to rely on the format in a more dynamic way, the good news is that Grav knows the unix timestamp so you can combine this knowledge with the pages format and on your rendering do something like:

``` twig
page.date|date(config.system.pages.dateformat.default)
```

Now every time you change the page date format, all your pages adapts by reflection, no matter if it's US `m/d/Y` or EU `d-m-Y`.

Hope this is what you were asking for.

**Comment by w00fz** [comment] 2016-02-10 20:35
Oh and also to answer @dimayakovlev , the `es6_revamp` branch also implements localization for the date picker which I think is what you were asking.

![date-time-picker](https://cloud.githubusercontent.com/assets/11734/12960928/b1b97be2-cff2-11e5-8347-2c848c5da4c4.png)

**Comment by nineteeneightyeight** [comment] 2016-02-12 16:30
Hi, I missed this before.

I'll try to explain the issue I encountered in a little more detail, just so you can tell whether that is fixed:

I had a news page. Under the news page I had children, each of which was a news article page. I wanted to order these articles on the news page by the `publish_date` set in the article (child page). When setting publish_date the date format was 10-02-2016 (d-m-y), however, this was being saved into the markdown as exactly that 10-02-2016 (d-m-y). This meant that when I was trying to order by `publish_date`, it wasn't working as intended because it expects the dates in `strtotime` format, so for the example used it was thinking the date was 2nd October 2016.

Therefore, the order: by: publish_date does not work if we are using d-m-y. What I was wondering is if during the save process it should change the dates always to y-m-d (so for the example used this would be 2016-02-10). This would ensure the date format was standardised and would work with the collection's order: by: functionality.

Does that make sense?

Cheers.

**Comment by dimayakovlev** [comment] 2016-02-12 17:07
@w00fz Yes, that's exactly what I was talking about. :)

**Comment by w00fz** [comment] 2016-03-03 23:08
The `es6_revamp` branch has been merged into `develop`, you'll get the localized datepicker in the next release version.

Cheers!

**Closed by w00fz** 2016-03-03 23:08 UTC
Labels: enhancement
