### ISSUE TITLE
Fixed behavior for "default" template

### ISSUE THREAD

**Issue by bitmatix** [getgrav/grav-plugin-admin#558] opened 2016-05-04 13:30 UTC
The shouldn't be a "default" template listed in the dropdown if the current theme doesn't have a default.html.twig file.

**Comment by rhukster** [comment] 2016-05-04 23:19
There was a very good reason we added 'default' to the list by default.  I can't quite remember the reasoning behind this right now.  I'll have to dig through the commit messages to get the details.  

Suffice to say, something bad will happen if its removed :)

**Comment by Kristjan-Reinsberg** [comment] 2016-05-17 10:59
Default is there so templates without blueprint can use default blueprint and also so blueprints can extend grav default blueprint. DISPLAYing the default template should be only if there is such twig template file. So Admin panel should make some sort of check and then act accordingly!

**Comment by rhukster** [comment] 2016-05-26 23:25
Well, no solution to this problem yet. but it's a duplicate of https://github.com/getgrav/grav-plugin-admin/issues/447

**Closed by rhukster** 2016-05-26 23:25 UTC
Labels: evaluating
