### ISSUE TITLE
Uncatched exception when trying to create an 'external' page.

### ISSUE THREAD

**Issue by sebikul** [getgrav/grav-plugin-admin#789] opened 2016-09-20 04:48 UTC
This is the backtrace shown. I could not isolate the issue to a specific input, to reproduce simply try to create a page with template `external`. If you need any more info please let me know!

```
Whoops\Exception\ErrorException thrown with message "Argument 1 passed to Grav\Common\Page\Page::move() must be an instance of Grav\Common\Page\Page, null given, called in /var/www/html/user/plugins/admin/classes/controller.php on line 1867 and defined"

Stacktrace:
#19 Whoops\Exception\ErrorException in /var/www/html/system/src/Grav/Common/Page/Page.php:877
#18 Whoops\Run:handleError in /var/www/html/system/src/Grav/Common/Page/Page.php:877
#17 Grav\Common\Page\Page:move in /var/www/html/user/plugins/admin/classes/controller.php:1867
#16 Grav\Plugin\AdminController:taskSave in /var/www/html/user/plugins/admin/classes/controller.php:186
#15 call_user_func in /var/www/html/user/plugins/admin/classes/controller.php:186
#14 Grav\Plugin\AdminController:execute in /var/www/html/user/plugins/admin/admin.php:313
#13 Grav\Plugin\AdminPlugin:initializeController in /var/www/html/user/plugins/admin/admin.php:360
#12 Grav\Plugin\AdminPlugin:onPagesInitialized in /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#11 call_user_func in /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:184
#10 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php:46
#9 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in /var/www/html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php:23
#8 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in /var/www/html/system/src/Grav/Common/Grav.php:310
#7 Grav\Common\Grav:fireEvent in /var/www/html/system/src/Grav/Common/Processors/PagesProcessor.php:20
#6 Grav\Common\Processors\PagesProcessor:process in /var/www/html/system/src/Grav/Common/Grav.php:121
#5 Grav\Common\Grav:Grav\Common\{closure} in /var/www/html/system/src/Grav/Common/Grav.php:396
#4 Grav\Common\Grav:Grav\Common\{closure} in /var/www/html/system/src/Grav/Common/Grav.php:372
#3 call_user_func_array in /var/www/html/system/src/Grav/Common/Grav.php:372
#2 Grav\Common\Grav:__call in /var/www/html/system/src/Grav/Common/Grav.php:122
#1 Grav\Common\Grav:measureTime in /var/www/html/system/src/Grav/Common/Grav.php:122
#0 Grav\Common\Grav:process in /var/www/html/index.php:45
```

**Comment by rhukster** [comment] 2016-09-21 16:13
Confirmed.  Looks like that is not working.

**Comment by rhukster** [comment] 2016-09-29 22:46
Fixed in Grav core.

**Closed by rhukster** 2016-09-29 22:46 UTC
Labels: bug
