### ISSUE TITLE
Error while trying to download (code: 0): https://getgrav.org/download/plugins/core-service-manager/1.0.20 Message: URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by RyoutaPL** [getgrav/grav-plugin-admin#1863] opened 2020-03-25 13:22 UTC
Error while trying to download (code: 0): https://getgrav.org/download/plugins/core-service-manager/1.0.20 Message: URL using bad/illegal format or missing URL

**Comment by rhukster** [comment] 2020-04-01 17:36
Duplicate of https://github.com/getgrav/grav-plugin-admin/issues/1847

**Closed by rhukster** 2020-04-01 17:36 UTC
