### ISSUE TITLE
BUG - [200]: POST /admin/task:keepAlive when Session Timeout is set

### ISSUE THREAD

**Issue by Rjgoolsby** [getgrav/grav-plugin-admin#1860] opened 2020-03-23 13:27 UTC
This is a bug report. When Session Timeout is set a [200]: POST /admin/task:keepAlive fires continuously eventually eating up all the resources in the browser and causing it to crash. If the value is empty or the default value it doesn't do this. 

To reproduce, input 31622400 seconds (1 year) in the session timeout and monitor the network tab. I'm using Google Chrome. See my attached photos. 

![Screen Shot 2020-03-23 at 9 24 36 AM](https://user-images.githubusercontent.com/10386821/77321404-89e63780-6ce8-11ea-830f-7a7a4060d14a.png)
![Screen Shot 2020-03-23 at 9 24 55 AM](https://user-images.githubusercontent.com/10386821/77321418-8c489180-6ce8-11ea-98b1-9c48a68140bb.png)

**Comment by rhukster** [comment] 2020-04-01 17:40
The keepalive is not really doing anything.  If resources are running out then it's probably a server issue.. ie memory leak in apache/php/nginx etc.

**Comment by w00fz** [comment] 2020-11-21 01:32
This was actually a legit issue caused by the browsers storing the delay of setTimeout as a 32-bit signed integer internally  (**2147483647 ms**). 
Setting anything greater than that, like your 1 year value (**31556925974 ms**), forces the setTimeout to fire the function immediately, causing tons of ajax calls to happen constantly until eventually it threw that error out. 

This is resolved in in 1.10 now.

Good catch!

**Closed by w00fz** 2020-11-21 01:32 UTC
Labels: bug
