### ISSUE TITLE
Saving completely custom page form

### ISSUE THREAD

**Issue by dandob74** [getgrav/grav-plugin-admin#1163] opened 2017-07-17 07:23 UTC
Hi,
saving a custom page [(grav doc)](https://learn.getgrav.org/forms/blueprints/example-page-blueprint#create-a-completely-custom-page-form) within the admin panel leads to the following exception.

Undefined index: folder in user\plugins\admin\classes\admincontroller.php line 464.

![image](https://user-images.githubusercontent.com/13012721/28258327-faae11f8-6ad0-11e7-8592-a6c6d2ddfe2b.png)

It looks like commit #d802b97 is the reason for this.

Best and thanks,
Daniel

**Comment by BTBTravis** [comment] 2017-07-17 13:51
I think line 465's conditional needs to check if $data['route'] isset.
I ran into the same problem this morning. 
`            if (!isset($data['folder'])) {
                $data['folder'] = $obj->slug();
                $this->data['folder'] = $obj->slug();
            }
`

**Comment by rhukster** [comment] 2017-07-17 16:11
Folder is a required field for the page, so your custom blueprint needs to include it (along with other required elements).

The best approach is to extend default then add your new things, in a new tab, you can even put that tab first if you like.

**Comment by flaviocopes** [comment] 2017-07-17 16:11
Looks a recent regression. PR https://github.com/getgrav/grav-plugin-admin/pull/1164 should fix the problem, can you give it a try?

**Comment by flaviocopes** [comment] 2017-07-17 16:25
You need to extend default, and use `unset` https://learn.getgrav.org/forms/blueprints/advanced-features#removing-fields-properties-unset to remove fields or tabs you don't want.

**Comment by flaviocopes** [comment] 2017-07-17 16:37
Thinking about it again, the documentation example works because it's setting the `route` parameter explicitly. The problem not extending `default` is that many useful information is lost, but `route` is the only mandatory one.

But it stopped working in 1.5.0, fixed in repo.

**Comment by ntopulos** [comment] 2017-07-18 13:27
All my forms stopped working after the update, I came across this issue, but the suggested solution wasn't satisfactory for my needs.

I want my users to be able to edit the content, but I also need to hide from them any advanced tab and field. This is the solution I found; adding the folder input with the type `hidden` :

            folder:
              type: hidden
              label: PLUGIN_ADMIN.FOLDER_NAME

**Closed** 2017-07-26 18:00 UTC
Labels: fixed in repo
