### ISSUE TITLE
select option group name ignores language strings

### ISSUE THREAD

**Issue by dani-ooo** [getgrav/grav-plugin-admin#2203] opened 2021-12-10 22:21 UTC
when naming option groups with a language string, either as `select` or `select_optgroup`, it’s not displayed as it should.

```yaml
form.field:
  label: THEME_X.LABEL
  type: select
  options:
    - THEME_X.SELECT_GROUP:
      - THEME_X.SELECT_OPTION1
```
in the example above, `THEME_X.SELECT_OPTION1` uses the corresponding language string, as expected, but `THEME_X.SELECT_GROUP` appears exactly as “THEME_X.SELECT_GROUP”. needless to say i made sure the string was in the theme’s `languages.yaml`.

**Comment by dani-ooo** [comment] 2021-12-11 06:02
i believe this will be solved by getgrav/grav-plugin-form/issues/540

**Comment by w00fz** [comment] 2022-02-04 22:10
This issue is not admin but form. Duplicate of getgrav/grav-plugin-form#540.

**Closed by w00fz** 2022-02-04 22:10 UTC
Labels: duplicate
