### ISSUE TITLE
Page creation error

### ISSUE THREAD

**Issue by DomBickus** [getgrav/grav-plugin-admin#1237] opened 2017-10-04 17:53 UTC
While creating a new page (parent page to be precise, modular page creation seems fine) gets to an error:
```
Whoops\Exception\ErrorException thrown with message "Cannot use Grav\Common\Utils as Utils because the name is already in use"

Stacktrace:
#0 Whoops\Exception\ErrorException in E:\Testavimo serveris\eds-www\projects\armontus\user\plugins\admin\classes\admincontroller.php:17
```
For testing purposes page created were named test:
![page-creation](https://user-images.githubusercontent.com/25031576/31191138-e9a4dba4-a945-11e7-9f8d-e5e64dc638e8.png)
And then it leads to an error:
![page-creation-error](https://user-images.githubusercontent.com/25031576/31191156-f6f8d4c2-a945-11e7-9f4e-2f96c46ed849.png)

**Comment by rhukster** [comment] 2017-10-04 18:47
I can't replicate this @DomBickus. Are you running any plugins other than admin/form/email/login? Which theme are you using?

**Comment by DomBickus** [comment] 2017-10-04 18:55
@rhukster I'm using custom made theme in development, although it's not it. I also use SEO plugin

**Comment by rhukster** [comment] 2017-10-04 18:56
Try disabling the SEO plugin, to see if that's the cause.

**Comment by DomBickus** [comment] 2017-10-04 18:58
@rhukster The plugin was the problem, need to inform the author.

**Comment by rhukster** [comment] 2017-10-04 19:19
Cool, thanks, closing this ticket then.

**Closed by rhukster** 2017-10-04 19:19 UTC
Labels: cannot recreate, more info needed
