### ISSUE TITLE
Session timeout issue

### ISSUE THREAD

**Issue by underr-ua** [getgrav/grav-plugin-admin#1515] opened 2018-09-11 17:54 UTC
I have a long term issue with short session timeout. Today i have tried to copy brand new copy of Grav + Admin Panel plugin without old config files and set the "Session timeout" to  43200sec, but this did not solve the problem - session timed out within 2 hours.

**Comment by mahagr** [comment] 2018-09-13 06:28
Duplicate of https://github.com/getgrav/grav-plugin-login/issues/178

**Comment by rhukster** [comment] 2018-10-01 23:47
This is fixed in Grav 1.5.2

**Closed by rhukster** 2018-10-01 23:47 UTC

**Comment by underr-ua** [comment] 2018-10-02 14:03
Unfortunately,  nothing changed for me with new version...
