### ISSUE TITLE
"First parameter must be URI" Twig_Error after clicking at "Pages" - v1.1.0-rc.2

### ISSUE THREAD

**Issue by 01010000101001100** [getgrav/grav-plugin-admin#664] opened 2016-06-12 14:06 UTC
```
Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("First parameter must be URI") in "pages.html.twig" at line 124.
```

![screen shot 2016-06-12 at 10 03 21 pm](https://cloud.githubusercontent.com/assets/4720153/15991598/ca55b988-30e9-11e6-98a9-9615c730a726.png)

My versions:
Grav - **v1.1.0-rc.1**
Admin plugin - **v1.1.0-rc.2**

**Comment by rhukster** [comment] 2016-06-12 20:28
Perhaps you can provide a copy of your `user/` folder zipped up so we can see what could be causing this error.  I'm unable to replicate this with my test sites.

**Comment by flaviocopes** [comment] 2016-06-13 07:19
Question: are you using Grav 1.0 or 1.1 rc ?

**Comment by 01010000101001100** [comment] 2016-06-14 07:50
@rhukster sure, how can I send it to you other than posting publicly here?

@flaviocopes I mentioned it both in title and topic itself 😛 I am running on **v1.1.0-rc.1**

**Comment by flaviocopes** [comment] 2016-06-14 08:14
@01010000101001100 I must be blind! Sorry

@01010000101001100 feel free to send it to me via a Gitter chat PM (upload directly, or post to Dropbox and post me the link)

**Comment by flaviocopes** [comment] 2016-06-16 14:27
Ok so as determined in the Gitter chat, this is caused by the View https://github.com/ellioseven/grav-plugin-view plugin.

**Comment by flaviocopes** [comment] 2016-06-16 14:40
Related to the use of `$types->scanBlueprints($locator->findResources(...))` instead of `$types->scanBlueprints($locator->findResource(...))` in that plugin, opening issue there.

**Comment by flaviocopes** [comment] 2016-06-16 14:45
Closing as tracked elsewhere.

**Closed by flaviocopes** 2016-06-16 14:45 UTC
Labels: bug, more info needed
