### ISSUE TITLE
Wrong parent in child page when using custom slug in parent

### ISSUE THREAD

**Issue by CoDanny** [getgrav/grav-plugin-admin#1068] opened 2017-04-14 11:28 UTC
If a parent page has a custom slug that's different than the folder name, all the child pages will have their Parent property set to Root when editing them

**Comment by flaviocopes** [comment] 2017-04-14 14:47
@rhukster looks like a regression introduced by https://github.com/getgrav/grav-plugin-admin/commit/7abf4b146155bd75b39cf68459d25f234d4af405, if you have an idea, or I'll check it out

**Comment by rhukster** [comment] 2017-04-14 15:28
Yah i'll look at this

**Comment by rhukster** [comment] 2017-04-14 17:36
Fixed in repo.

**Closed by rhukster** 2017-04-14 17:36 UTC
Labels: bug
