### ISSUE TITLE
Grav makes downloaded .zip files invalid

### ISSUE THREAD

**Issue by Dakicka** [getgrav/grav-plugin-admin#437] opened 2016-03-03 09:06 UTC
hi,
I've set up Grav on a shared hosting provider (running PHP version 5.6.17).

When I download .zip files through the Grav web frontend, it throws an error that they are invalid when I try to open them. I tested it with FIrefox and IE, on Ubuntu, Win and OS X.

The nice guys of the shared hoster helped me already troubleshooting this issue. If I download the same .zip directly via HTTP or via SSH, the file is fine. 
If I use the MD Link, the file gets downloaded as well but is corrupt.

Here is the link to a file on my page that  I'll get using the Grav website:
`http://studytipps.de/notendurchschnitt-berechnen/Gesamtnote.zip`

And here is the direct HTTP link on the webserver:
`http://studytipps.de/user/pages/01.studytipps/notendurchschnitt-berechnen/Gesamtnote.zip`

If you need any further information, please let me know. I would really like to solve that problem.

**Comment by flaviocopes** [comment] 2016-03-03 20:12
To me both links work fine.

Is this happening when you upload the Zip via the Admin plugin to the page media? Or are you uploading the zip file to the page folder directly? If you didn't try this last method yet, can you try and report if the zip is still corrupted?

**Comment by Dakicka** [comment] 2016-03-03 21:39
have you tried to open the .zip file from the first link? The download works but the file is invalid... I uploaded it via SFTP. Don't really use the Admin plugin.
Tested it again just now, still doesn't work for me on my devices...

**Comment by rhukster** [comment] 2016-03-03 21:43
Files unzip for me on my local.  What are you using to unzip?

**Comment by Dakicka** [comment] 2016-03-03 21:59
Windows ZIP as well as 7-Zip and standard Unarchiver on OS X. All with Error.

**Comment by rhukster** [comment] 2016-03-03 22:04
I tested with Unarchiver, standard Archive utility and also Keka unarchiver.  It's definitely not a native issue, it's more likely it's specific to your webserver/hosting environment.  I'm sure if you copy your site local it will work fine.

**Comment by Dakicka** [comment] 2016-03-03 22:16
yes, it works on my local test environment. Have you any ideas where to look on the hosting environment? With a costum PHP script which only pass through the file it works fine on the hoster as well as with the direct download link...

**Comment by w00fz** [comment] 2016-03-04 19:33
I see the first link you posted being a broken zip. However I think this is still related to your server setup and how it's serving files.

What hosting provider are you using?

**Comment by Dakicka** [comment] 2016-03-04 20:09
Hi, I use uberspace.de

**Comment by Dakicka** [comment] 2016-03-05 08:39
UPDATE:
I just tested the download of the .ZIP files on my local environment again, using XAMPP. I get the same, invalid, .ZIP files. So I don't think the shared hoster is the problem here.

I used the inheritance tutorial to customize my theme like described on the [Grav page](http://learn.getgrav.org/themes/customization#theme-inheritance).

I just figured out, when I switch back to the Antimatter theme, the files are working fine.
I only did very very little customizations on my theme and only in the CSS section. Where in the Theme could be the cause of this problem?

**Comment by flaviocopes** [comment] 2016-03-05 09:39
Ah good you were able to replicate locally. Post me the `user/` folder via PM in Gitter, I'll check what's causing the issue.

**Comment by flaviocopes** [comment] 2016-03-05 10:19
Replicated, it's caused by theme inheritance. 
Happens to any zip file.

Easy way to replicate: in the active theme (e.g. `antimatter`) config yaml, instead of 

```
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      paths:
        - user/themes/antimatter
```
set

```
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
       '':
         - user/themes/antimatter
```

**Comment by rhukster** [comment] 2016-03-05 19:10
ok thanks for tracking down the usecase @flaviocopes.  Looks like a weird one, but legit.  We'll investigate.

**Comment by rhukster** [comment] 2016-03-07 00:35
Well i'm having trouble getting it to corrupt with the streams config.  I'll check with the guys tomorrow.

**Comment by mahagr** [comment] 2016-03-07 07:35
Oh, I may be able to see why its happening. The issue is that those two formats `paths` vs `prefixes` do not merge correctly; you need to use one or another format..?

**Comment by flaviocopes** [comment] 2016-03-07 08:30
This stripped-down user folder recreates the problem with the minimum amount of files.

[user.zip](https://github.com/getgrav/grav-plugin-admin/files/160968/user.zip)

Try downloading `/test/LICENSE.zip`

**Comment by rhukster** [comment] 2016-03-07 18:45
Ok should be fixed with the very minor correction above.  You can try it in your own installation.

**Closed by rhukster** 2016-03-07 18:45 UTC
Labels: bug

**Comment by Dakicka** [comment] 2016-03-07 18:53
It works! Thank you very much!

**Comment by edwarr99** [comment] 2016-11-30 21:39
Hello!  I'm experiencing what I believe is the same problem as above.  PDF files are downloaded okay but anything else (.zip / .doc) files are reporting as corrupted when downloaded.  Is there a corrective action I can take avert this?
