### ISSUE TITLE
Can't scroll on any of the admin panel pages

### ISSUE THREAD

**Issue by angelogiomateo** [getgrav/grav-plugin-admin#808] opened 2016-10-03 17:35 UTC
When I attempt to scroll on any of the admin panel pages, it won't move down. Only when I zoom out of the page, I can access any of the content near the bottom of the page. I can scroll down in the text box, but not the actual page itself.

![image](https://cloud.githubusercontent.com/assets/8495631/19047019/10b812cc-896e-11e6-9d44-3cea2786f739.png)

![image](https://cloud.githubusercontent.com/assets/8495631/19047070/46e38714-896e-11e6-8f10-22a99a3f2525.png)

**Comment by w00fz** [comment] 2016-10-03 18:17
You probably have a JS Error, try opening the developer tools and see what the error is.

**Comment by angelogiomateo** [comment] 2016-10-03 18:41
Hi w00fz,

I'm getting this error:
![image](https://cloud.githubusercontent.com/assets/8495631/19049200/6c1fecd0-8977-11e6-8154-3aa2e80f48f8.png)

**Comment by w00fz** [comment] 2016-10-03 18:51
That doesn't look like a js error that would prevent the page from scrolling.
Have you tried another browser like chrome to see if it's isolated to your current one?

**Comment by angelogiomateo** [comment] 2016-10-03 19:25
Doesn't seem to work either on Edge.

**Comment by angelogiomateo** [comment] 2016-10-03 19:28
Doesn't work on Firefox too.

**Comment by w00fz** [comment] 2016-10-03 19:38
Ok when you opened the developer tools, was it after the page had loaded? Because you need to first open the dev tools and then refresh the page, in order to catch JS errors.
So maybe there are JS errors.

**Comment by angelogiomateo** [comment] 2016-10-03 20:01
Did that too. No other JS errors.
I'm wondering if it's my domain?

**Comment by flaviocopes** [comment] 2016-10-04 08:15
I remember another user had issues when using Cloudflare, probably their compression or JS minification is giving some problems. Can you check this is the case, by disabling cloudflare on the site?

**Comment by angelogiomateo** [comment] 2016-10-04 18:06
Tried disabling Cloudflare. Still doesn't seem to be working, though I wonder if it takes time to respond to the change. Will let you know in a bit.

**Comment by angelogiomateo** [comment] 2016-10-04 18:06
whoops sorry.

**Comment by angelogiomateo** [comment] 2016-10-04 18:08
UPDATE: It is definitely Cloudflare. I wonder what's going on with that. Issue solved, but I guess that's a bug that mods might want to look into.

**Comment by w00fz** [comment] 2016-10-04 18:34
Yah this seems just to be an issue with Cloudfare JS optimization service. Nothing we can do really.

This also appears to be a duplicate of #797.

**Closed by w00fz** 2016-10-04 18:34 UTC
Labels: duplicate

**Comment by flaviocopes** [comment] 2016-10-05 09:16
Is there a way to have it NOT act on Admin, but just on the frontend?

**Comment by OleVik** [comment] 2017-02-02 00:06
For future reference, per CloudFlare's current setup (of names and settings): In CloudFlare's interface, go to Speed and disable Rocket Loader (or through a page-rule). Also, @flaviocopes, yes, it [can be disabled in the (default) 'automatic' mode](https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-) with a data-attribute on scripts: ` <script data-cfasync="false" src="/javascript.js"></script>`.

Though honestly adding this for all <script>-tags seems excessive to me, it would be more efficient if CloudFlare detected a singular HTML5-tag and disabled based upon that. Though I guess Grav could leverage assets to add the attribute based on an option in system.yaml.

An example of a page-rule would be the URL match `olevik.me/staging/*/admin`, where the `*` is a wildcard indicating any folder-name. For settings, add "Rocket Loader" and select "Off".
