### ISSUE TITLE
infinite wheel on homepage

### ISSUE THREAD

**Issue by reyman** [getgrav/grav-plugin-admin#52] opened 2015-08-11 13:50 UTC
Hi,
My install have two days, i try to install a theme and some plugin, but something is wrong now, i have an infinite wheel on the home page ... as you can see.

http://these.sebastienreycoyrehourcq.fr/

Grav version 0.9.35

List of plugins : 

 Admin Panel  v0.2.0
 Email  v0.1.0
 Error  v1.2.2
 Form  v1.0.0
 Highlight  v1.2.0
 Login  v0.1.0
 Problems  v1.1.6
 Smileys v1.1.0
 Themes Preview v1.2.1
 Toc v1.2.0

Theme : 

 Foundation v1.0.5
Antimatter  v 1.7.0

Any advice to repair that ?

**Comment by flaviocopes** [comment] 2015-08-11 13:59
I'll close this as not an issue of the admin plugin specifically. Please first try uninstalling some plugins one by one and the unused theme, to detect which one could be the cause the problem, then post on the forum (http://getgrav.org/forum).

**Closed by flaviocopes** 2015-08-11 13:59 UTC
