### ISSUE TITLE
move_uploaded_file moves file to inexistent directory

### ISSUE THREAD

**Issue by z38** [getgrav/grav-plugin-admin#432] opened 2016-02-28 12:56 UTC
Today, I tried to upload my first file using the admin plugin. Unfortunately, the upload fails when I try to upload `picture.jpg` to the page `01.home`.

The request to `http://localhost/admin/media/home.json/task:addmedia` returns:
```json
{
    "error":{
        "type":"Whoops\\Exception\\ErrorException",
        "message":"move_uploaded_file(\/var\/www\/user\/pages\/home.json\/picture.jpg): failed to open stream: No such file or directory",
        "file":"\/var\/www\/user\/plugins\/admin\/classes\/controller.php",
        "line":644
    }
}
```
As far as I see, if `move_uploaded_file` would move the file to `/var/www/user/pages/01.home/picture.jpg` the upload should work fine.

I'm using Grav 1.0.10, admin plugin 1.0.9, Apache 2.4.7 and PHP 5.5.9.

**Comment by flaviocopes** [comment] 2016-02-28 13:02
Could be a permission issue? http://learn.getgrav.org/troubleshooting/permissions

**Comment by z38** [comment] 2016-02-28 13:45
Yeah, at first I thought of that too. I think the problem is that there is no directory `/var/www/user/pages/home.json/`. The content and media files are in `/var/www/user/pages/01.home/`.

**Comment by flaviocopes** [comment] 2016-02-28 17:46
Which web server are you using?

**Comment by flaviocopes** [comment] 2016-02-28 17:52
Cannot reproduce. Can you zip and post me your `user/` folder via a Gitter PM, so I'll try to recreate with your exact setup?

**Comment by z38** [comment] 2016-02-28 22:13
Thanks for looking into it. After digging around, I found that I removed all page types in `user/config/system.yaml` months ago. Now it works: 
```yaml
pages:
  # ...
  types: [json]
  # ...
```
I removed those entries as it wasn't clear to me why a page like `/home.json` or `/home.atom` should be served. It seems that it's just the same HTML output with a different `Content-Type`. Do you know what's the purpose of those pages?

**Comment by rhukster** [comment] 2016-02-29 18:13
These are the types that Grav is configured to handle via the URL.  The admin makes use of JSON extension on pages to perform AJAX requests.  That is why `json` is one of the valid field types.  Removing that will break ajax used in any plugin (as Grav supports but doesn't use any AJAX.

So that explains the problems you were seeing. Closing now we have know what the issue is.

**Closed by rhukster** 2016-02-29 18:13 UTC

**Comment by z38** [comment] 2016-03-03 13:03
Oh I see, thank you for the explanation!
