### ISSUE TITLE
Page preview with PHP build-in server not working

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav-plugin-admin#2] opened 2015-08-05 10:13 UTC
I cloned grav, did bin/grav install, bin/gpm install admin and run locally with php -S localhost:8000
I had a question regarding the admin plug-in and editing of pages; with the above setup there's just home to edit. There's an 'eye' icon and I was suspecting this is to 'preview' the editing? However, when clicking nothing happens except that for a few seconds a red widget appears saying "Not found". So my question is what is the purpose of the "eye" button and why is it saying "Not found". Should I install something extra?

**Comment by flaviocopes** [comment] 2015-08-05 10:22
Replicated on the PHP built-in server (php -S localhost:8000). Works fine in MAMP

**Comment by w00fz** [comment] 2015-08-05 17:23
Duplicate of #3 even if this came up before :)

**Closed by w00fz** 2015-08-05 17:23 UTC
Labels: duplicate
