### ISSUE TITLE
Login plugin not updating

### ISSUE THREAD

**Issue by angelogiomateo** [getgrav/grav-plugin-admin#807] opened 2016-10-03 17:32 UTC
When I'm in the admin panel, it is telling me that there is an update available for the login plugin. However, when I attempt to update the plugin, it is stuck on the Update Loading module. I'll keep it on to attempt updating it for close to 20 minutes, but there is still no change.

![image](https://cloud.githubusercontent.com/assets/8495631/19046966/dd1b67fc-896d-11e6-996e-988f9b9701fe.png)

**Comment by flaviocopes** [comment] 2016-10-04 08:14
Can you open the browser console, and see if there is any error showing up?

**Comment by angelogiomateo** [comment] 2016-10-04 18:08
UPDATE: It is definitely Cloudflare. I wonder what's going on with that. Issue solved, but I guess that's a bug that mods might want to look into.

**Comment by flaviocopes** [comment] 2016-10-05 09:16
Is there a way to have it NOT act on Admin, but just on the frontend?

**Comment by flaviocopes** [comment] 2016-10-10 16:54
Closing as not directly caused by the Admin plugin

**Closed** 2016-10-10 16:54 UTC
