### ISSUE TITLE
"Successful logout" message disappears in Grav 1.1.0-beta.2.

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav-plugin-admin#546] opened 2016-05-03 07:12 UTC
I don't know if it's wanted or not, but the "Successful logout" message has gone away.

In Grav 1.0.10 
![screenshot at mai 03 09-05-43](https://cloud.githubusercontent.com/assets/6952638/14976759/cc815776-110e-11e6-9247-3910bfbd1be6.png)

In Grav 1.1.0-beta2 
![screenshot at mai 03 09-07-28](https://cloud.githubusercontent.com/assets/6952638/14976768/d93886a6-110e-11e6-83ae-939b2a9893a2.png)

**Comment by flaviocopes** [comment] 2016-05-03 08:52
Mmm cannot replicate this, I can see the message

**Comment by RomainFallet** [comment] 2016-05-03 09:08
I took a video that shows the bug, starting with a fresh install https://www.youtube.com/watch?v=c_XK-eyWYtc&feature=youtu.be

**Comment by flaviocopes** [comment] 2016-05-03 10:13
Ok got it too now!

**Comment by rhukster** [comment] 2016-05-03 14:36
I've seen this too, but thought it was my setup as no one else was getting it.  Now we know it's legit, we can find the culprit and fix.  Thanks.

**Comment by flaviocopes** [comment] 2016-05-03 18:19
Fixed in https://github.com/getgrav/grav-plugin-admin/commit/b8c8b47823d207b89c175ddd365b9dde81eef112, was caused by a recent (25 days ago) change.

Was only happening when Grav was in a subfolder, and not in a vhost, that's why I never noticed this!

**Closed by flaviocopes** 2016-05-03 18:19 UTC
Labels: bug, language
