### ISSUE TITLE
All site redirects wiped out when incomplete form fields submitted

### ISSUE THREAD

**Issue by dabonde** [getgrav/grav-plugin-admin#1741] opened 2019-08-22 01:15 UTC
There seems to be an issue when updating the site config, particularly When updating "redirects and routes". 

In the image below you can see that I've added a new entry to the custom redirects, and the new entry has the "/your/alias" populated, but not the "/your/redirect". 
![image](https://user-images.githubusercontent.com/9524091/63478381-00118a00-c4cd-11e9-8e4d-6b55d3e6b29d.png)
At this point, if you hit save it will wipe out all the existing redirects. 

I've had a client wipe them out twice these past 2 weeks, and sporatically in the past at which point I've had to delve into our backups to restore them. I only replicated this today after playing around with the submission a few times. 

Seems a little odd that this has occurred for me as often as it has. I wonder if there are other circumstances around the form submission that can wipe out the existing redirects.

**Comment by georgewilli-am** [comment] 2019-08-23 03:19
This seems to be an issue across Array forms input types, I can reproduce this with redirects, routes and metadata in pages.

**Comment by w00fz** [comment] 2019-08-23 06:29
Have you tested this in the latest beta releases? I believe I have fixed this recently with beta-5 when sorting out another issue with arrays in nested lists.

https://github.com/getgrav/grav-plugin-admin/blob/1.10/CHANGELOG.md#08112019

**Comment by georgewilli-am** [comment] 2019-08-23 15:54
Just pulled beta-5 and was able to reproduce this with that too, same issue in the form data:
```
data[metadata][key]: val
data[metadata]: 
```

 (Didn't pull beta Grav version, not sure if that's relevant)

**Comment by w00fz** [comment] 2020-11-17 05:26
This is fixed with https://github.com/getgrav/grav-plugin-admin/commit/ed8f24a8e77eae4e87cd53f5964658da3c473918 (see also #1972)

**Closed by w00fz** 2020-11-17 05:26 UTC
Labels: evaluating
