### ISSUE TITLE
Private Browsing in Safari doesn't allow localStorage and throws JS errors

### ISSUE THREAD

**Issue by Quy** [getgrav/grav-plugin-admin#527] opened 2016-04-28 16:00 UTC
For example, under System>Content, `Long display date format` is cut off and you can't scroll pass this point to see the other options.

**Comment by rhukster** [comment] 2016-04-28 18:26
Thanks, we'll have a look at this.

**Comment by rhukster** [comment] 2016-04-28 18:41
What version of the admin are you on?  

We did some major rework of mobile support in the 1.1.X beta of the Admin and this works on iOS, I just tested on my phone, works fine in Safari and Chrome.

**Comment by Quy** [comment] 2016-04-28 19:05
v1.1.0-beta.2 test release. Downloaded from here: https://www.getgrav.org/downloads

**Comment by rhukster** [comment] 2016-04-28 19:57
What browser? I can't replicate this.. Working fine on my iphone and on the iOS Simulator for ipad.

**Comment by rhukster** [comment] 2016-04-28 19:59
http://www.giphy.com/gifs/26AHxusTBd7JlViY8

**Comment by Quy** [comment] 2016-04-28 20:21
Not working with Safari on iOS 9.3.1 (iPad)
Working on iPhone 6s but not iPhone 4s

**Comment by Quy** [comment] 2016-04-28 20:29
I connected the iPad to a MacBook Pro and in Safari>Develop, here are errors that may be related to the issue:
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota..`setItem - admin.min.js:4:21701`
Failed to load resource: the server responded with a status of 404 (Not Found)...`user/plugins/admin/themes/grav/js/vendor.min.js.map`
Failed to load resource: the server responded with a status of 404 (Not Found)...`user/plugins/admin/themes/grav/js/admin.min.js.map`

**Comment by rhukster** [comment] 2016-04-28 20:48
Well that's interesting! I'll hand this over to our resident JS expert to have a look at.

**Comment by rhukster** [comment] 2016-04-28 20:52
Are you using private browsing? i googled, and seems like that might be an issue.  The admin does use local storage in places to store info and states.

**Comment by rhukster** [comment] 2016-04-28 20:54
Yup, i can recreate with private browsing.  I think this limits a lot of functionality for storing state locally, so this is simply not going to work with the admin.  Just use regular browsing mode and it should work fine.

**Comment by Quy** [comment] 2016-04-28 21:02
Confirmed that private browsing is the culprit. Thank you!

**Comment by w00fz** [comment] 2016-04-28 21:14
Reopening and editing the title.

Thanks.

**Comment by rhukster** [comment] 2016-04-29 16:38
Closing as we can't really fix this.

**Closed by rhukster** 2016-04-29 16:38 UTC
Labels: bug

**Comment by w00fz** [comment] 2016-05-03 18:40
I actually fixed this now, so stay tuned for next beta.

Only note of consideration is that you will still see an error in the console that is caused by `debugbar` of which we really don't have control over. However I did test and admin still works fine, quite likely you won't only be able to use the debug bar.

Cheers.
