### ISSUE TITLE
Dynamic update pagemediaselect fields when pagemedia file is uploaded

### ISSUE THREAD

**Issue by maximelebreton** [getgrav/grav-plugin-admin#741] opened 2016-08-18 21:13 UTC
When an image is uploaded with `pagemedia` , `pagemediaselect` fields on the same page aren't  dynamically updated.

![animation](https://cloud.githubusercontent.com/assets/1072425/17790748/3dacb08e-6598-11e6-9247-b45117741686.gif)

**Comment by rhukster** [comment] 2016-08-18 23:21
This kinda goes hand in hand with your other issue: https://github.com/getgrav/grav-plugin-admin/issues/740

Really you would have to create a custom field with some JavaScript that got the images list from **pagemediaselect** field and adds it to your image dropdown.  This is not something that we can build in really.

**Comment by maximelebreton** [comment] 2016-08-19 11:15
I dont think it's related.
If you upload a media trough **pagemedia**, and you have a **pagemediaselect** field in the same page, this field should be updated.
It's not a question, but a design problem.

**Comment by flaviocopes** [comment] 2016-08-22 11:29
This can be improved by firing a javascript event when the the page media are updated (added/removed), so the pagemediaselect field items can be refreshed

**Comment by fredrikekelund** [comment] 2016-08-29 12:25
+1

**Comment by fredrikekelund** [comment] 2016-08-29 12:40
This is probably a duplicate of #450

**Comment by flaviocopes** [comment] 2016-08-29 13:12
Currently working on it https://github.com/getgrav/grav-plugin-admin/pull/750

**Comment by w00fz** [comment] 2016-10-01 07:05
This is implemented

**Closed by w00fz** 2016-10-01 07:05 UTC
Labels: enhancement
