### ISSUE TITLE
Cannot add new page

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#54] opened 2015-08-12 07:12 UTC
If  I am trying to add a new page without parent page (parent is root):
```
Whoops\Exception\ErrorException thrown with message "Call to a member function path() on a non-object"
Stacktrace:
#0  in D:\OpenServer\domains\grav\user\plugins\admin\classes\admin.php:525
```
If I am trying to save a new page with parent:
![Errors](https://cloud.githubusercontent.com/assets/8279974/9218300/e5a4fe0c-40d9-11e5-8fd5-c5c90a3dc3a6.png)
I am using local webserver with Apache/2.2.29 (Win32) and PHP 5.4.35.

**Comment by rhukster** [comment] 2015-08-12 12:46
Not sure if this is related, but do you have param separator set to `;` in your system configuration?

**Comment by reyman** [comment] 2015-08-12 14:28
same here, impossible to create a new page using root :(

**Comment by flaviocopes** [comment] 2015-08-12 14:38
I cannot replicate - just to make sure, is everything (grav & admin plugin) up to date?

**Comment by rhukster** [comment] 2015-08-12 14:44
I cannot reproduce either.  I am able to save a new page with parent set to root.

**Comment by rhukster** [comment] 2015-08-12 14:45
@reyman are you on windows also??

**Comment by reyman** [comment] 2015-08-12 16:10
no i'm on linux

**Comment by reyman** [comment] 2015-08-12 16:12
Bug arrive not at save, but when i want to publish : 'Validation failed: Invalid input in Process'

I Create a page 
I Save the page
I Change visibility
Eror

**Comment by dimayakovlev** [comment] 2015-08-12 16:14
@rhukster separator is ;

**Comment by flaviocopes** [comment] 2015-08-12 16:15
@reyman I think this is fixed in Grav 0.9.37, you're on that?

**Comment by dimayakovlev** [comment] 2015-08-12 16:32
With Grav 0.9.37 I can create subpages without errors.

**Comment by reyman** [comment] 2015-08-12 17:38
@flaviocopes i'm on 0.9.37 and i update today the 'php bin/gpm selfupgrade -f'

**Comment by rhukster** [comment] 2015-08-12 17:39
Just to confirm this issue you are seeing is **only** on root level pages? subpages are fine?  What exactly are you doing when you create the page? Can you provide me step-by-step instructions on how you get this error.  I need to be able to reproduce it before I can fix it.

**Comment by dimayakovlev** [comment] 2015-08-12 17:57
Yes, after upgrade to Grav 0.9.37 I can create supbages without errors.

An error occurs only when creating root level page.

1.Сlick Add Page button
2.Fill Add Page form. Parent Page is Root
3.Click Continue button

Error:
```
Whoops\Exception\ErrorException thrown with message "Call to a member function path() on a non-object"

Stacktrace:
#0  in D:\OpenServer\domains\grav\user\plugins\admin\classes\admin.php:525
```

**Comment by rhukster** [comment] 2015-08-14 20:52
Ok, i'm going to have to ask you to test this again with Grav 0.9.38 when it's released (soon).  I have reworked the admin class so the line number is not really that helpful from 0.9.37.

**Comment by rhukster** [comment] 2015-08-15 15:17
Also out of curiosity can you create it as a subpage and then move it to root?

**Comment by dimayakovlev** [comment] 2015-08-15 18:14
@rhukster Yes, moving subpage to root works fine.

**Comment by rhukster** [comment] 2015-08-17 04:33
Can you please provide me with a zip file of your `user/` folder.  I really need to work out if you have something special in your setup because I still can't replicate this error.

**Comment by Sommerregen** [comment] 2015-08-17 07:27
@rhukster I really suspect that this is again a `param_sep` issue - at least the error looks quite familiar for me. If I'm right I should fail creating a page on my Windows machine, too. I will try that out and leave you a message as soon as possible here.

**Comment by rhukster** [comment] 2015-08-17 11:34
I think your right, i was in the process last night of getting my windows VM running again to test it there.  If you have one operational and can help debug it, that would be awesome.

**Comment by dimayakovlev** [comment] 2015-08-17 14:07
@rhukster Here it is http://1drv.ms/1E03bih

**Comment by Sommerregen** [comment] 2015-08-17 19:08
@rhukster I just tested on Apache/2.4.7 (Win7) PHP/5.4.25 with `param_sep: +` (but it shouldn't make any difference) with the latest develop branch and creating pages is possible. However I will try to figure it out. Maybe there are some remnants, which are not `param_sep` compliant.

**Comment by rhukster** [comment] 2015-08-19 00:11
Are you going to submit a PR based on your fork with those minor fixes?

**Comment by Sommerregen** [comment] 2015-08-19 07:38
Yes, I will do it. I just have had no time to look at it and see, if I have not overlooked anything. I will submit one this evening!

**Comment by rhukster** [comment] 2015-08-19 14:04
Just saw another instance of this error:

![grav_page_error](https://cloud.githubusercontent.com/assets/1084697/9358359/ce539ba4-4648-11e5-8f60-c071d9c30528.png)

Looks like this one is with Ammps and grav is in it's own subdirectory.

**Comment by Sommerregen** [comment] 2015-08-19 18:14
Ok, just prepared a PR for you ;-) Concerning your error report, I have another minor issue (not really important) and happens when I try to point my browser to an unknown path (see the address bar):

![error](https://cloud.githubusercontent.com/assets/9073307/9364866/bbe1851a-46ae-11e5-8042-6b769cdcf293.png)

**Comment by rhukster** [comment] 2015-08-19 18:57
Should be fixed! Please create new issues for any other windows bugs

**Closed by rhukster** 2015-08-19 18:57 UTC
Labels: bug
