### ISSUE TITLE
Could not delete page when using search filter

### ISSUE THREAD

**Issue by K232** [getgrav/grav-plugin-admin#83] opened 2015-08-20 06:30 UTC
On the pages overview I enter a search filter in the upper right. Now I want to delete one of the displayed pages. Admin Panel asks to confirm and I click 'Continue'. Now I get another popup (Firefox) asking whether I want to stay on the site or leave it. When I click on 'stay', popup disappars but page is still there. When I click on 'Leave', a new page opens: I contains the url of the page I want to delete, added by '/taskdelete'. So Admin Panel asks me to create a new page called 'taskdelete'.
Workaround: Open the single page in Admin Panel and click 'Delete' there works fine.

**Comment by rhukster** [comment] 2015-08-20 20:12
This one requires some @w00fz skills.. assigning to him..

**Closed** 2015-08-21 18:44 UTC
Labels: bug

**Comment by w00fz** [comment] 2015-08-21 18:45
You actually weren't supposed to get the "Changes detected, are you sure you want to leave?" popup. The modal asking to confirm you wanted to delete was the only intended one.

This should be now fixed and behave as intended originally.
