### ISSUE TITLE
Saving with invalid data makes blueprint fields disappear

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-admin#2068] opened 2021-02-15 16:12 UTC
* Create a new page blueprint and add some fields (I've used inheritance, if that matters)
* Set some fields to required
* Go to admin panel and create a new page
* Enter some data, but not the required field
* Save
* You will get a few errors, but the additional blueprint fields disappeared.
* Save again
* The fields are there again, but some data is lost (not all for some reason)

**Comment by mahagr** [comment] 2021-02-16 08:53
I had to manually remove the required attribute from the form field, but even then I'm not able to reproduce the issue. All fields are there and filled up with the content I wrote.

You need to give me a specific example. Also, are the fields coming from a plugin or from the form definition?

**Comment by NicoHood** [comment] 2021-02-16 20:28
This sample should work (its a stripped down version of my real file):
https://gist.github.com/NicoHood/74573cb550deaa36c3768a8ed13686b8

I've added this to `/themes/quark/blueprints/bikefitter2.yaml`

Check, if that helps to reproduce.

**Comment by mahagr** [comment] 2021-02-17 08:34
Yup, I'm able to reproduce the issue now.

**Comment by mahagr** [comment] 2021-02-17 12:36
Fixed in https://github.com/trilbymedia/grav-plugin-flex-objects/commit/3dcc618fad19cab0689e8eedf6dbb461514b82f7

**Closed** 2021-02-17 18:36 UTC
Labels: 1.10, bug, fixed in repo
