### ISSUE TITLE
Layout bug in Themes

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-admin#1001] opened 2017-02-27 03:40 UTC
Found today:
![image](https://cloud.githubusercontent.com/assets/7556290/23347957/27c9f548-fcfa-11e6-9f27-c4d5bb5487ee.png)

In action:
![grav_themes](https://cloud.githubusercontent.com/assets/7556290/23347991/70cfbb74-fcfa-11e6-9273-b883d665d1ee.gif)

Grav v1.1.17 
Admin v1.2.14
Tested in last Chrome and FF

**Comment by flaviocopes** [comment] 2017-02-27 08:30
Can you test with latest develop? I committed https://github.com/getgrav/grav-plugin-admin/commit/618e830a1a3ab057b99b566c3e040688302a408e a couple days ago, I don't see the "Activate" problem any more.

**Comment by flaviocopes** [comment] 2017-02-27 08:31
http://g.recordit.co/ZSQVYyRasU.gif

**Comment by Sogl** [comment] 2017-02-28 14:51
Need to check. How to quickly switch to development build?

**Comment by flaviocopes** [comment] 2017-02-28 20:37
Easiest thing is download https://github.com/getgrav/grav-plugin-admin/archive/develop.zip and unzip in user/plugins/admin.

Otherwise cloning from Git, and checking out the `develop` branch.

**Comment by rhukster** [comment] 2017-03-06 17:41
The activate issue is fixed (jumping up and down)

The columns 'issue' is not really an issues.. the output uses 3 columns until the with is narrow, then switches to 2 columns, then 1 for very small widths. This is expected behavior. It only looks a little weird, because it spreads out the 2 cards in in 3 column mode. If you added a 3rd theme, it would make much more sense.

**Closed by rhukster** 2017-03-06 17:41 UTC
