### ISSUE TITLE
Empty meta tag inserted in header if there's no metadata in config

### ISSUE THREAD

**Issue by jpfleury** [getgrav/grav-plugin-admin#187] opened 2015-09-17 18:58 UTC
Say in *Configuration - Site - Metadata* we have only one metadata set:

description: My description

Grav will insert this HTML code in the page header:

    <meta name="description" content="My description" />

Now, in *Configuration - Site - Metadata*, delete the content of the only metadata and save. We will have this:

![capture d ecran_2015-09-17_14-51-56](https://cloud.githubusercontent.com/assets/687082/9942927/facfb004-5d4b-11e5-8a4e-73b54168da1d.png)

The problem is that Grav will add an empty `<meta />` in the page header, so the HTML code is invalid.

**Comment by rhukster** [comment] 2015-09-17 20:19
And if you hit the minus sign to delete the row and save?

**Comment by jpfleury** [comment] 2015-09-17 20:56
It doesn't work. I wanted to fill a bug report about that. When there's only one row:

![](https://cloud.githubusercontent.com/assets/687082/9942927/facfb004-5d4b-11e5-8a4e-73b54168da1d.png)

the minus sign does nothing.

If I add an empty row with the plus sign:

![02](https://cloud.githubusercontent.com/assets/687082/9945701/cb9133c4-5d5c-11e5-9c59-2da25d23e7c1.png)

then delete the non-empty row with the minus sign (it works because there are more than one row):

![03](https://cloud.githubusercontent.com/assets/687082/9945718/e7c7c58a-5d5c-11e5-9423-4a685ab9d25f.png)

then save, the deleted row appears again. It's not deleted:

![](https://cloud.githubusercontent.com/assets/687082/9942927/facfb004-5d4b-11e5-8a4e-73b54168da1d.png)

**Comment by flaviocopes** [comment] 2015-09-18 10:00
The minus sign does not work because it's the last one, so if you delete that last one there's no way to add one again. Might remove `-` altogether on the last item.

Emptying the values however should not generate a `0` in the key. I thought it was caused by a recent change made to the metadata field, but it's not. Looking into it

**Comment by jpfleury** [comment] 2015-09-18 10:03
When there's only one row, the minus sign may clear values in the fields.

**Comment by flaviocopes** [comment] 2015-09-18 10:06
Good one

**Comment by flaviocopes** [comment] 2015-09-18 12:21
Posted a PR for this: https://github.com/getgrav/grav/pull/332

Also fixed the minus sign with clearing values in https://github.com/getgrav/grav-plugin-admin/commit/374f6c17e7ee043af521589f2cc7d9eeb4e990d4

**Comment by rhukster** [comment] 2015-09-18 16:08
Should be good now.. closing.

**Closed by rhukster** 2015-09-18 16:08 UTC
Labels: bug, fixed in repo
