### ISSUE TITLE
My zip-files aren't zip-files anymore – says the page-media-upload

### ISSUE THREAD

**Issue by kontaktemusikverlag** [getgrav/grav-plugin-admin#2157] opened 2021-06-22 13:08 UTC
Hello grav team!
There must have been an update between march and now, that has destroyed the upload-function for zip-files!
I  use 7-zip since i can think, not having changed any configuration!

When i now drag'n'drop zip-files onto the page-media-upload-area, the file uploads and then at the end it stops with the FILE_ERROR_UPLOAD
> The mime type does not match to file extension

Even files, that i uploaded until march without any problem now aren't zip files anymore – based on your upload-check.
What am i doing wrong? What can i do or what can you do to make the drag'n'drop-upload work again?

Thanks.

![2021-06-22 grav plugin admin upload problem 01](https://user-images.githubusercontent.com/84339788/122929818-a77ed280-d36b-11eb-85f3-5bab6b2cefcc.jpg)

**Comment by mahagr** [comment] 2021-06-23 05:53
Please check the mime type that your browser uses for the files, I'm curious what it is.

- zip uses `application/zip`
- 7z uses `application/x-7z-compressed`

**Comment by kontaktemusikverlag** [comment] 2021-06-23 07:40
Please tell me, how I can check the mime type that all my browsers (Firefox, Chrome, Opera, Edge) suddenly seem to use wrong for zip-files?
I use the 7-zip-software for zipping zip files, not creating 7z-files.

**Comment by mahagr** [comment] 2021-06-23 09:46
If you inspect the HTTP requests, you should see XHR request when you upload a file. It should have a `Content-Type` header, check the contents of it.

**Comment by kontaktemusikverlag** [comment] 2021-06-23 10:36
Okay, thank you. 
When i upload a zip-file the „task:addmedia“ is started and the XHR response header says:

> Content-Type: multipart/form-data; boundary=---------------------------274659125231687689742823215255

![2021-06-23 grav plugin admin upload problem 02](https://user-images.githubusercontent.com/84339788/123082714-9e4f3d80-d41f-11eb-8b61-3160b8752b7d.jpg)

**Comment by mahagr** [comment] 2021-06-24 12:37
Thanks. The type looks correct; I have to dig deeper what causes this issue for you.

**Comment by mahagr** [comment] 2021-06-24 12:40
I am able to upload zip files in page admin (Page Media section).

@kontaktemusikverlag How can I reproduce the issue? Do other zip files work for you, or is it every zip file?

**Comment by kontaktemusikverlag** [comment] 2021-06-24 13:17
Thank you, for me it is every zip-file (different sizes from nearly zero to a few MB does't make differences) trying to be uploaded via the page media section.
I have not much time at the moment, i will have a look tomorrow if i can provide you more information.

**Comment by kontaktemusikverlag** [comment] 2021-06-25 08:46
Hello Matias,
now i had the time to make a fow more tests. And i found out, where the header said
> Content-Type: multipart/form-data
there are more tabs, and the „params“-tab seems to split the multipart/form-data in the single-parameter, where my „testfile.zip“ and all others are recognized as „application/x-zip-compressed“
> Content-Disposition: form-data; name="file"; filename="testfile.zip"
> Content-Type: application/x-zip-compressed

![2021-06-25 grav plugin admin upload problem 03](https://user-images.githubusercontent.com/84339788/123393626-8eaa3300-d59e-11eb-9a08-408f553d398d.jpg)

So for the moment i could help me with setting the „zip“-MIME-Type at „admin/config/media“ to „application/x-zip-compressed“ after i was not able to make a second entry for „zip“. That way it works for me for now.

But that doesn't explain, what changed and when, that all browsers since a few months have the upload-problems even with files being uploaded without errors months before.

**Comment by pamtbaau** [comment] 2021-07-03 09:34
Not the same file type but similar issue when uploading a *.js file.

I've commented the 'js' line in section `uploads_dangerous_extensions` in _security.yaml_ to be able to upload, but then the error message mentioned above appears.
> The mime type does not match to file extension

The request labelled 'task:addMedia' shows the following content-type in its header: `Content-Type: application/json`.

Browser: Chrome 91+

**Comment by Verequies** [comment] 2021-08-13 03:48
Can confirm this issue on Windows. Works fine on every Linux and macOS system I have tried. Not sure what caused this but last working at least for me on the 3rd August.

**Comment by mahagr** [comment] 2021-08-13 08:49
Duplicate of https://github.com/getgrav/grav/issues/3422 (needs to be fixed in Grav)

**Closed** 2021-09-15 08:49 UTC
Labels: duplicate, fixed
