### ISSUE TITLE
Form and multi-language in modular page

### ISSUE THREAD

**Issue by ekiwnox** [getgrav/grav-plugin-admin#821] opened 2016-10-11 16:04 UTC
Hi guys,

I have a problem with a form in a module for a modular page. I needed a special form, so I decided to create it with blueprint. It works quite nice without the multi-language, but when I save the filled form in a specific language, the default form appears and the content of my own form is deleted...

The form perfectly works if I don't select a specific language... but I really need it in two languages. 

Here's a link with the video of the issue : 
https://youtu.be/bOd2xs0RShs

Hope I'm clear ! Sorry for my english (I'm not a native speaker)

Here's the code of my form : 
```
title: columns-module
form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        gallery:
          type: tab
          title: Worker
          fields:
           header.worker:
              name: Worker
              type: list
              style: vertical
              label: Add a new worker
              fields:
                .name:
                  type: text
                  label: name
                .history:
                  type: text
                  label: history
```

**Comment by flaviocopes** [comment] 2016-10-11 16:16
Hi, I saw this problem 3 times in 24 hours :) so I am familiar with this as it's same as https://github.com/getgrav/grav-plugin-admin/issues/819#issuecomment-252951591 

Can you test this fix I pushed yesterday (but not yet released) is what you need? https://github.com/getgrav/grav-plugin-form/commit/55dbb18bceb0d42b21005dfdf51da5e2de3db700

Let me know so I can push a release of Form

**Comment by ekiwnox** [comment] 2016-10-11 16:27
Hi again ! Thank you so much for you fast reply ! 
I tried your solution but unfortunately it doesn't work for me ! It has the same behaviours as before.

I have noticed that when I save the page with my own form, it doesn't save in any language like the other pages. Maybe that can help you to find the issue ? :-)

**Comment by rhukster** [comment] 2016-10-11 23:50
Duplicate of https://github.com/getgrav/grav-plugin-admin/issues/819 - please use that one issue.

**Comment by flaviocopes** [comment] 2016-10-12 16:41
This is in the backend, or in the frontend?

**Comment by ekiwnox** [comment] 2016-10-12 16:55
In the backend, here's the video of the behaviour of the issue : 
https://youtu.be/bOd2xs0RShs

**Comment by flaviocopes** [comment] 2016-10-12 17:01
Sorry I had intention to view it but I missed it! Then it's a different issue

**Comment by flaviocopes** [comment] 2016-10-12 17:03
Is the above snippet the whole content of your page yaml ?

**Comment by ekiwnox** [comment] 2016-10-13 07:37
Yes it's all the content of my page yaml... ! Maybe I done it wrong ? :-(...

**Comment by flaviocopes** [comment] 2016-10-13 09:40
No, it should work fine. I just tested it. The page once saved returns to the original layout, and all is fine. 

Grav and Admin and all the other plugins are all up to date?

**Comment by ekiwnox** [comment] 2016-10-13 11:40
Yes ! I don't know why It doesn't work. I also retried with a reseted Grav Admin and same behaviour... :-(
<img width="1700" alt="capture d ecran 2016-10-13 a 13 36 42" src="https://cloud.githubusercontent.com/assets/22773938/19347637/1eb0a3e2-914a-11e6-9f16-0df64216e329.png">

**Comment by flaviocopes** [comment] 2016-10-13 11:54
Send me your user/ folder via gitter.im/flaviocopes and I'll try that directly.

**Comment by flaviocopes** [comment] 2016-10-13 13:12
Ok replicated it locally

**Comment by flaviocopes** [comment] 2016-10-13 13:28
So the issue happens when 

1) you save the file as `columns-module.md`
2) you enable multilanguage
3) you switch to another language, at that point instead of creating `columns-module.it.md` (for example), it creates `columns-mod.it.md` (truncating the template name, so it loses that information)

I could not replicate as I was enabling multilang prior to creating the page, so I had `columns-module.en.md` and it was saved correctly. 

Going to fix that issue.

**Comment by flaviocopes** [comment] 2016-10-13 14:44
Should be fixed in Admin now! If you can try putting the `develop` branch in `user/plugins/admin` and report back, appreciated 👍

**Closed** 2016-10-13 14:43 UTC
Labels: bug, replicated

**Comment by ekiwnox** [comment] 2016-10-16 16:27
Hi  flaviocopes ! Thank you so much ! 
I don't understand what to do ! What's the develop branch ?

**Comment by flaviocopes** [comment] 2016-10-17 12:42
On this page https://github.com/getgrav/grav-plugin-admin click the "Download" button and you'll get a package of the development version of the Admin plugin. You can put under user/plugins/admin to replace the currently available version.

But nevermind if you don't feel confident doing so, just wait for the release.

**Comment by ekiwnox** [comment] 2016-10-19 12:26
It works for me ! :-) Thank you so much !
