### ISSUE TITLE
v1.10.0-rc.19 - Fieldset sub fields are blank

### ISSUE THREAD

**Issue by zouloux** [getgrav/grav-plugin-admin#1997] opened 2020-12-08 16:51 UTC
Hi, I just updated admin plugin from v1.10.0-rc.17 to v1.10.0-rc.19 and discovered a small issue.
Forms with `fieldset` does not show page content (sub fields of fieldset are blank).
Reverting `themes/grav/templates/forms/fields/fieldset/fieldset.html.twig` file to v1.10.0-rc.17 patch the issue.
I needed to clear cache to see changes.
Thanks

**Comment by w00fz** [comment] 2020-12-10 07:09
Thanks, I believe this is a duplicate of https://github.com/getgrav/grav-plugin-admin/issues/1995

**Comment by mahagr** [comment] 2020-12-10 12:53
See fix in the another issue.

**Closed by mahagr** 2020-12-10 12:53 UTC
Labels: duplicate
