### ISSUE TITLE
“Cannot connect to the GPM” error in admin interface

### ISSUE THREAD

**Issue by timmmmmmmmm** [getgrav/grav-plugin-admin#507] opened 2016-04-20 13:32 UTC
After installing Grav + admin plugin on a shared webhosting everything seems to work, however on every admin page I get the error "Cannot connect to the GPM".
I explained my problem [at the forums of Grav](https://getgrav.org/forum#!/general:cannot-connect-to-the-gpm_1) and after making sure that Curl and OpenSSL are enabled I got the advice to open an issue here.

I have no SSH available, installed the package both with direct upload and unzipping the package using a PHP script. I tried to recreate the actions in [the permission fixing script](https://learn.getgrav.org/troubleshooting/permissions) over FTP, but still no luck.

**Comment by k1ngf15h3r** [comment] 2016-05-15 19:41
same issue by me with grav + skeleton. Installed Admin panel over cli and can use gpm on cli but in the backend I got "cannot connect to the gpm". on an other site hosted in a seperated virtual host on the same server are no issues with this. second site was created with core grav and manual added theme

**Comment by flaviocopes** [comment] 2016-05-16 07:05
We haven't yet found the cause of this. Since two sites on your same server have different behavior, I wonder what are the differences.

Folder permissions?

Some difference in the PHP settings? Try making a diff of the 2 `/admin/config/info` pages, if something is different in the two environments

**Comment by briankb** [comment] 2016-05-22 05:06
This just happened to me as well. I'm on Windows 10 machine running XAMPP with only the Apache module running. Things were working fine then I made a new branch in git and it started showing that error. I switched back to master where everything was working but still get the error. 

The only thing I can figure out that changed was between the final commit to master (after getting things working) I added a .gitignore to ignore cache/ and logs/ folders. While double checking the user/config/system.yaml I noticed cache: enabled: true so maybe something was being stored in cache but when I blew out the changes and went back to master it caused a conflict... I have since set cache:enabled to false but that hasn't resolve the GPM error issue. 

I turned off Windows Firewall and restarted Apache, confirmed the default page loaded but GPM error still exists when you log into admin.

I don't think it's a proxy issue, as suggested in the forum but I don't know what else to check.

**Comment by flaviocopes** [comment] 2016-05-23 08:30
I tried XAMPP (on OSX). 

After setting the permissions correctly (change owner and group of `htdocs`) and setup Apache to run as my OSX user / group in `httpd.conf`, things run fine, I get no GPM error.

Could surely be a permission issue, so check this first. I followed http://constant.co.za/fix-permissions-on-xampp-osx/

**Comment by flaviocopes** [comment] 2016-05-23 08:32
Also try MAMP on windows, if you get the same problem

**Comment by wondie** [comment] 2017-03-31 03:50
Same here for me too.

**Comment by mahagr** [comment] 2020-12-01 19:56
I believe this one has been fixed in Admin 1.10.

**Closed by mahagr** 2020-12-01 19:56 UTC
Labels: bug
