### ISSUE TITLE
Issues on edit page

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-admin#97] opened 2015-08-25 05:23 UTC
Admin 0.4.1
![untitled](https://cloud.githubusercontent.com/assets/8279974/9459300/89c974f4-4b02-11e5-8862-59d807db3dda.png)
![untitled 2](https://cloud.githubusercontent.com/assets/8279974/9459301/8c2b2116-4b02-11e5-880d-8ee07d1ca975.png)

**Comment by dawidxt** [comment] 2015-08-25 06:11
I have similar issue after updating page.

![grav](https://cloud.githubusercontent.com/assets/13783466/9459877/cc1beb22-4b00-11e5-8e58-9b6958e27e98.png)

**Comment by flaviocopes** [comment] 2015-08-25 07:31
@dawidxt @dimayakovlev can you try
1) disable all caching plugins
1) clear all the Grav cache
2) clear the Browser cache

and tell me if you still see those issues?

**Comment by dimayakovlev** [comment] 2015-08-25 07:44
@flaviocopes There are no additional plugins were installed. Nothing changes after I cleared all caches. Still no WYSWYG editor and Media management in Normal mode.

**Comment by flaviocopes** [comment] 2015-08-25 09:08
Ah @dawidxt I just noticed - Opera is still untested, but with version 31 it works fine since it's Chromium based. Which version is that? Does Chrome/Firefox give the same error?

**Comment by flaviocopes** [comment] 2015-08-25 09:09
@dimayakovlev (sorry this same issue is now containing 2 separate problems) - I think it can depend on the theme. Which theme is that? And is that a page of type Blog?

**Comment by dawidxt** [comment] 2015-08-25 09:09
@flaviocopes here same, except it seems like clearing caches fixed the position of language switcher, now is in right place. 

Thought I am having two issues:
1. While I am in English pages, I see pages with different language also with coresponding tag, but while I am in the other language, I don't see the english one.

2. I see a bug while I am in dashboard and I click >> next to grav logo. Its trying to redirect me to " http://name.pl/grav/en/1" and sometimes it gives me 404 page error, but sometimes it gives me error like that 
"
RuntimeException
HELP
SplFileInfo::getMTime(): stat failed for /home/users/dawidxt/public_html/name.pl/grav/user/plugins/admin/pages/admin/1.md
"

**Comment by dawidxt** [comment] 2015-08-25 09:12
@flaviocopes yea, I am using opera 31. But after clearing cache, the position of lang switcher seems to be ok placed. Still I am having tab called "value" instead of "content". I am using original animatter theme which came with Grav. And I installed new grav and admin plugin via update in dashboard.

**Comment by dimayakovlev** [comment] 2015-08-25 09:22
@flaviocopes it seems that it is really theme problem. No issues with Antimatter v1.7.2.

**Comment by flaviocopes** [comment] 2015-08-25 09:40
@dimayakovlev might be the theme blueprint for the blog page. ([theme]/blueprints/blog.yaml) try changing that to the antimatter's one

@dawidxt ah right, that's a string translation issue - I fixed in the develop branch, will release an update shortly.

**Comment by flaviocopes** [comment] 2015-08-25 09:46
@dawidxt the link is a problem introduced in the last update, thanks for reporting! The lang issue, on the other hand, I cannot reproduce it. Can you paste the system.yaml languages configuration?

**Comment by dawidxt** [comment] 2015-08-25 09:58
Glad I could help somehow.
Here is the system file.
http://www.filedropper.com/system_1

**Comment by flaviocopes** [comment] 2015-08-25 12:14
@dawidxt if a page is already translated (e.g. you have default.en.md and default.pl.md), then it shows both languages. Otherwise you need to create the new lang version by clicking the dropdown 'Save as [lang]' beside the Save button on top

**Comment by dawidxt** [comment] 2015-08-25 13:46
@flaviocopes I could do that, but after clearing caches (I guess) I don't have any visible option in the drop down menu. I checked this on latest Opera and Chrome - none of them seems to be working.

![a860c4d6-4b01-11e5-910a-a1a04b49a959](https://cloud.githubusercontent.com/assets/13783466/9468154/3c7cdc48-4b40-11e5-9d99-f089dfdfc216.png)

**Comment by rhukster** [comment] 2015-08-25 13:50
Opera is completely untested, can you show the issue with Chrome? Also what version of Chrome?

**Comment by dawidxt** [comment] 2015-08-25 13:55
I updated above post

**Comment by rhukster** [comment] 2015-08-25 14:00
You know the most helpful thing would be to zip up your site and give us a link to the zip file so we can try a local installation. Can PM us the location on gitter.im.

**Comment by flaviocopes** [comment] 2015-08-25 14:35
@dawidxt confirmed it's a bug, fixing ti

**Comment by dawidxt** [comment] 2015-08-25 15:09
@flaviocopes super :)

**Closed** 2015-08-25 16:24 UTC
Labels: bug, evaluating

**Comment by flaviocopes** [comment] 2015-08-25 16:25
@dawidxt to reply to the last question, it's the theme that defines other fields for that page type (Blog, in this example)
