### ISSUE TITLE
Normal/Expert change in the Admin Plugin

### ISSUE THREAD

**Issue by andreasmaucher** [getgrav/grav-plugin-admin#268] opened 2015-11-11 23:02 UTC
Page View: 
![expert](https://cloud.githubusercontent.com/assets/10424014/11105650/937625cc-88d0-11e5-95c6-d88e89b2c55b.JPG)
At the German language the container for the german word "Expertenansicht" is to small

**Comment by lukasluecke** [comment] 2015-11-12 19:39
This is a duplicate of #252

**Closed** 2015-11-12 19:40 UTC
Labels: ui
