### ISSUE TITLE
Unexpected error messages on Save

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#626] opened 2016-05-28 15:00 UTC
I've started to use the updated Frontmatter editor in b5, and I am seeing some unexpected error messages when I try to Save.

For example:
![2016-05-28_06-44-11](https://cloud.githubusercontent.com/assets/1812771/15627900/ce4d7452-24a7-11e6-9c4c-38e65b564251.png)

When trying to save this page:
```
---
title: Home
blog_url: blog
body_classes: header-image fullwidth

sitemap:
    changefreq: monthly
    priority: 1.03

modular_content:
    items: '@self.modular'
    order:
        dir: desc

content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 14
    pagination: true

feed:
    description: Course Hub Description
    limit: 10

pagination: true
---

```

Earlier I seemed to get a bit different message with the same Frontmatter (this is the image I shared in the Gitter room):
![2016-05-26_06-18-34](https://cloud.githubusercontent.com/assets/1812771/15627929/68f51410-24a8-11e6-8d55-98eaf1ac311d.png)

I've also attached the full user folder (which I am testing with b5).

Thanks very much,
Paul
[user.zip](https://github.com/getgrav/grav-plugin-admin/files/287759/user.zip)

**Comment by JohnMica** [comment] 2016-05-28 20:38
same here and here is the link to user folder https://www.dropbox.com/sh/0udjvi217if75w8/AAB4wznbMLJcepADkoO987dWa?dl=0

hope it help figuring out what is going on.

i have 3 blog.ro.md pages, 2 work with no errors on save the 1 under blog folder is showing error when saving (similar to Paul

**Comment by flaviocopes** [comment] 2016-05-30 13:20
The `sitemap.priority` value expects a string, so enclose the value in quotes, like `" "`. This will work.

On the other hand, the "Max Item Count" problem is an actual bug. Looking at it.

**Comment by flaviocopes** [comment] 2016-05-30 13:23
The problem is in the blog.yaml definition in the theme blueprints.. using `type: int` fails, using `type: number` works. Not sure why `type: int` fails in expert mode but works in normal mode.

**Comment by paulhibbitts** [comment] 2016-05-30 13:37
Hi Flavio, thanks very much for looking into it. I can verify both suggestions work on my Grav install.

BTW, is there a way to apply this change to a Blueprint within an _inherited_ theme vs. the original source theme? Just wondering if I can somehow make this change in my inherited theme until the source theme gets updated. Thank you.

**Comment by flaviocopes** [comment] 2016-05-30 15:47
Yes I think you can just copy the `[template]/blueprints/blog.yaml` file to your theme, and edit it.

**Comment by paulhibbitts** [comment] 2016-05-30 16:06
Thanks Flavio, I just tried that but no go, the original error re-occurs :-( Is that a supported use case and a bug or something not actually supported? It would be a very useful technique!

**Comment by flaviocopes** [comment] 2016-05-30 16:09
I thought it worked, as it's for templates.. never tried actually! So not sure. Needs to be fixed in Admin btw I think, rather than in the theme

**Comment by rhukster** [comment] 2016-05-30 18:19
Ok this is fixed in two parts:

1) Validation for sitemap priority should of been 'float' not 'string'.  That has been rereleased.

2) Validation was defaulting to `Validation::typeText()` for all fields that didn't have a function defined, this was incorrect.  Skips the function check if it doesn't exist now. https://github.com/getgrav/grav/commit/4fbf4329fdf53689943fe1ccaf3f581c01f9e65c

**Closed by rhukster** 2016-05-30 18:19 UTC
Labels: bug, in progress...

**Comment by paulhibbitts** [comment] 2016-05-30 19:10
Thank you!
