### ISSUE TITLE
Readme access for plugins in Admin page

### ISSUE THREAD

**Issue by finanalyst** [getgrav/grav-plugin-admin#1477] opened 2018-06-26 08:31 UTC
When a plugin is downloaded, the local `user/plugins/<plugin>` contains the README.md file associated with the current version of the plugin.

However, the local README.md cannot be accessed from the Admin window. If you open the plugin information, you see (and can click on) the README file in the plugin's repository.

Could a link be installed in the quicklinks to the local README for each plugin?

**Comment by OleVik** [comment] 2018-06-27 21:38
Seemingly duplicate of #1114, and links to README as shown on each extension-page:

![image](https://user-images.githubusercontent.com/974717/42001005-e6cb3a56-7a62-11e8-8063-ceeb6c0a9e9a.png)

Not the local one, as that is locked down as not accessible, but you should add argumentation in favor in that issue.

**Comment by finanalyst** [comment] 2018-06-28 02:14
Why is local README not accessible? I am only suggesting this for a user with admin access, someone who most probably could delete the plugin.

Accessing github is not instantaneous, but the file exists locally, so why use bandwidth to get it again from github?

Finally, there is the question of versioning. Suppose, for some reason, a site administrator has decided NOT to update to the latest version of the plugin. A link to the github repo will always give the most recent version, whilst the local README will always be the one associated with the version installed.

**Comment by OleVik** [comment] 2018-06-28 13:05
It just is not currently, but as mentioned in the linked issue it easily could be, and the link to the README could easily link to the tag rather than the master-branch - which is version-specific and will yield the README for the currently installed version of the plugin.

**Comment by rhukster** [comment] 2018-06-30 21:15
Duplicate of #1114 really, so will leave that one open and close this.

**Closed by rhukster** 2018-06-30 21:15 UTC
Labels: enhancement
