### ISSUE TITLE
Admin themes page cards with different image heights

### ISSUE THREAD

**Issue by jakefb** [getgrav/grav-plugin-admin#875] opened 2016-11-24 23:58 UTC
Hi,

On the themes page in the admin, when there are themes with different thumbnail heights, the activate button on the card is not displayed at the bottom of the card

Not too important just a visual thing, but would be nice if it was fixed :)

![Image of admin themes](http://imgur.com/yLJinJsl.png)

**Comment by flaviocopes** [comment] 2016-11-25 17:35
Which browser are you using? It's fine on Chrome OSX

**Comment by jakefb** [comment] 2016-11-26 02:27
I'm running Chromium Version 54.0.2840.100 (64-bit) on linux

**Comment by pieplu** [comment] 2017-04-28 19:27
Hi! With the same setup, I can't reproduce the bug. (On available theme and installed theme)

`Version 58.0.3029.81 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)`

![image](https://cloud.githubusercontent.com/assets/3260285/25543965/84c1b5d2-2c26-11e7-9947-d51508e7d1a3.png)

**Comment by flaviocopes** [comment] 2017-05-01 16:36
It's been recently fixed by https://github.com/getgrav/grav-plugin-admin/pull/1067

**Closed by flaviocopes** 2017-05-01 16:36 UTC
Labels: browser, ui
