### ISSUE TITLE
Non-standard template lost when page is edited

### ISSUE THREAD

**Issue by rosolar** [getgrav/grav-plugin-admin#707] opened 2016-07-17 11:05 UTC
This issue occured with a page using the Receptar skeleton. When editing the page sidebar/about, which uses the template "widget", this template setting is lost when saving the modified page and template "Blog" is used. This yields an error during rendering.

Version: grav-1.1.1, admin-plugin-1.1.2, receptar-1.2.0

**Comment by flaviocopes** [comment] 2016-07-18 12:08
The problem is that the theme does not provide a Widget blueprint, so Admin does not find it in the list, and defaults to the first one it finds (Blog).

I committed a fix: https://github.com/getgrav/grav-theme-receptar/commit/4353eeb7280823f0b52cd54e25be57a5b25c05a4

Can you download the new theme zip from https://github.com/getgrav/grav-theme-receptar/archive/develop.zip and put it in your `user/themes` folder, and let me know if this is fixed for you too?

**Comment by rhukster** [comment] 2016-07-20 20:28
Please reopen if this does not answer your concern.

**Closed by rhukster** 2016-07-20 20:28 UTC

**Comment by rosolar** [comment] 2016-07-25 17:47
Sorry for the late answer. Yes, the fix solves my problem. Thank you for the prompt reaction!
