### ISSUE TITLE
Grav 1.7 RC.3 Small problems

### ISSUE THREAD

**Issue by MohamedAlwash** [getgrav/grav-plugin-admin#1816] opened 2020-01-22 14:13 UTC
Hello every one! After trying Grav 1.7 RC.3 it looks very nice and I love it. I can't wait until it's stable. Only the next things that doesn't work in admin panel.
1. i.e when I safe a page in default it doesn't save when I refresh the page.
2. Some pages are not visible but when I look in the settings of the page under advanced tab it show me that visible is enabled.
3. When I make a new page it doesn't load the blueprint.
4. When I'm editing a page at under each tab you see some text with radio button as you can see on the picture. And why do I see empty tabs also?
![unknown](https://user-images.githubusercontent.com/56513986/72901283-c538aa00-3d29-11ea-95fb-c584cf2d1393.png)

So far this is what I found

**Comment by Mohamed-Programmer** [comment] 2020-01-24 08:56
5. When ["Flex Object"](https://github.com/trilbymedia/grav-plugin-flex-objects) plugin is enabled the pages on admin panel keeps loading after logging on not super user.  As you can see on picture.
![Capture](https://user-images.githubusercontent.com/56513986/73056596-c1269c80-3e8f-11ea-84d8-2320948d1a13.PNG)

**Comment by mahagr** [comment] 2020-01-28 12:59
I believe I found the cause of this issue. Do you have a multi-site setup?

Can you provide URL to the page as well as look into the HTML source:

```html
    window.GravAdmin.config = {
        current_url: 'GIVE ME THIS VALUE',
```

Are the URLs the same?

**Comment by Mohamed-Programmer** [comment] 2020-01-28 13:23
Sorry, I don't have that knowledge what you are asking. I do not really understand where to look. First of all I don't have multi-site setup.

And this is what you looking right?
![Capture](https://user-images.githubusercontent.com/56513986/73267471-6b2c5e80-41d9-11ea-8b05-22fbef3e72a2.PNG)

When I console.log I get the next info. Is this what you are looking for?
![Capture](https://user-images.githubusercontent.com/56513986/73267561-9adb6680-41d9-11ea-9eae-b276d91795a5.PNG)

**Comment by mahagr** [comment] 2020-01-28 14:26
You're getting 403 Forbidden. Likely your user does not have permissions for page admin.

This is something I'm working on right now, so wait for next RC or use super admin.

**Comment by Mohamed-Programmer** [comment] 2020-01-28 14:30
Oke, thank you!

**Comment by mahagr** [comment] 2020-01-28 14:39
On the other issues, how can I reproduce those? I need minimal instructions to test the issues, please.

**Comment by Mohamed-Programmer** [comment] 2020-01-28 15:04
Of course no problem.
First one: When I open a page to change the content. I get this [red warning](https://user-images.githubusercontent.com/56513986/73274711-4d192b00-41e6-11ea-9fd6-6fdd72f0e8de.PNG).
What I do to avoid this I change for example some text and save it as default instead of Nederlands or English. But when I reopen the page to change the content again it give me the same warning as you can see on the picture. My console also shows [this](https://user-images.githubusercontent.com/56513986/73275604-a9307f00-41e7-11ea-8081-13ff8cb5f782.png).

**Comment by mahagr** [comment] 2020-08-28 18:57
Many of the issues mentioned here have already been resolved. I'm closing this issue, if you find more, please open individual issue for each bug. If you just have questions, it is better to use our discord chat to get answers to your questions.

**Closed by mahagr** 2020-08-28 18:57 UTC
Labels: 1.10, bug
