### ISSUE TITLE
Unable to remove theme

### ISSUE THREAD

**Issue by PSiAU** [getgrav/grav-plugin-admin#44] opened 2015-08-10 09:44 UTC
I found something which may be a bug. All the files are owned by the web server so I don't believe it's a permissions issue (I hope!).

Steps to recreate:
1) Install any theme
2) Try to uninstall it. The error message "Cannot delete non-existing folder." comes up and the theme remains installed.

**Comment by flaviocopes** [comment] 2015-08-10 13:31
I cannot reproduce it, what's your server setup?

**Comment by PSiAU** [comment] 2015-08-10 13:49
My setup is as follows. I know it can be optimised with other components like php-fpm but i'm happy with it for dev work.
Debian 7.8
Apache 2.2
PHP 5.4 running as mod_php

Apache runs as www-data. Grav is installed in /var/www/html/grav01. That entire directory and everything under it is owned by www-data.
All components have been installed from the official apt repos.
It's a very simple setup, nothing complicated (IMHO) about it.

**Comment by flaviocopes** [comment] 2015-08-10 13:58
Is the theme symlinked, or you just installed it through the admin?

**Comment by PSiAU** [comment] 2015-08-10 14:00
I installed it through the admin.
It's a completely fresh install of Grav 0.9.35, with the admin plugin installed first, followed by Theme installation and attempted removal. Nothing else was done to it.

**Comment by flaviocopes** [comment] 2015-08-10 14:11
Strange, I just recreated the process you followed but all works fine. Let's wait if @rhukster has ideas of what could be

**Comment by PSiAU** [comment] 2015-08-10 14:26
Something which may or may not be related is when I click on an installed but unactivated theme, there is a Save button in the top right corner. Upon clicking it throws the error "Validation failed: enabled is not defined in blueprints".

**Comment by flaviocopes** [comment] 2015-08-10 14:31
That is going to be fixed in the next round of theme releases, it's already fixed in the themes repositories - got the same error on save, but the uninstall works fine.

**Comment by rhukster** [comment] 2015-08-10 15:02
Hmm. i can't replicate this also. I really am not sure what it could be other than permissions.

**Comment by rhukster** [comment] 2015-08-10 15:03
can you for testing purposes set the theme to be 777 and see if you can delete via the admin?  This will rule out permissions being the issue

```
$ chmod 777 -R themename/
```

Cheers.

**Comment by PSiAU** [comment] 2015-08-11 02:29
Nope, didn't help :(

**Comment by rhukster** [comment] 2015-08-11 03:52
ok, well that actually helps. One other thing, I'm sure the GPM command from the console to remove the theme doesn't work either?

```
$ bin/gpm uninstall yourtheme
```

**Comment by PSiAU** [comment] 2015-08-11 03:56
That actually worked!

**Comment by rhukster** [comment] 2015-08-11 04:07
Oh ok, then we definitely have narrowed it down to the admin plugin then.  That will help. I'll see if flavio can take a look tomorrow morning his time.

**Comment by PSiAU** [comment] 2015-08-11 04:08
Awesome. Thanks for taking the time to look into it :)

**Comment by flaviocopes** [comment] 2015-08-11 10:05
@PSiAU can you add this line 

`var_dump($target); var_dump(is_dir($target)); var_dump(is_file($target)); var_dump(file_exists($target)); exit();`

to system/src/Grav/Common/Filesystem/Folder.php, before line 246? In short, before the highlighted line here: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Filesystem/Folder.php#L246

Then try to remove the theme again, and let me know what's the output you get in the page.

**Comment by PSiAU** [comment] 2015-08-11 12:19
Sure thing. This is the result:
bool(false) bool(false) bool(false) bool(false)

**Comment by flaviocopes** [comment] 2015-08-11 12:45
Strange! It seems it cannot even find the theme folder. Can you put in this line https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/gpm.php#L130 

```
var_dump($location); var_dump(Installer::lastErrorCode()); exit();
```

And tell me the output?

**Comment by PSiAU** [comment] 2015-08-11 13:13
This is the result:
bool(false) int(4)

**Comment by flaviocopes** [comment] 2015-08-11 13:15
Uhm.... replace that same line with

```
var_dump($package->package_type); var_dump($package->slug); exit();
```

I get, when deleting Afterburner2:

`string(6) "themes" string(12) "Afterburner2"`. You?

**Comment by flaviocopes** [comment] 2015-08-11 13:16
I didn't ask, but which browser are you using?

**Comment by PSiAU** [comment] 2015-08-11 13:17
This is what I get:
string(6) "themes" string(6) "Agency"

I'm using Safari 8, but I've also tried this with Chrome 44 and it does the same thing.

**Comment by flaviocopes** [comment] 2015-08-11 13:24
Really strange. Removing any plugin from the admin-side works fine, or same issue?

**Comment by PSiAU** [comment] 2015-08-11 13:27
I hadn't tried that before......so I just gave it a shot then (removed the Email plugin), and i get a runtime exception:
One of the required plugins is missing or not enabled

**Comment by PSiAU** [comment] 2015-08-11 13:30
Haha that's actually killed my whole admin panel.

**Comment by flaviocopes** [comment] 2015-08-11 13:30
Ah that's actually because it's required by the admin plugin (should put up a warning prior to delete a plugin with dependencies). Reinstall it using `bin/gpm`. What about a "normal" plugin, for example Feed?

**Comment by PSiAU** [comment] 2015-08-11 13:33
After a fresh install and installing the Feed plugin, I was able to successfully disable it, but not uninstall it. It gave the same error:
Cannot delete non-existing folder.

**Comment by flaviocopes** [comment] 2015-08-11 13:40
Tracked it down to Locator::findResource() not finding plugins or themes during uninstall. @rhukster any ideas what could it be, maybe the Streams config not being setup properly?

**Comment by rhukster** [comment] 2015-08-11 22:12
It just makes no sense that it works for everyone else, but not for one person. Is it possible to try a newer version of PHP?  I've tested 5.4.43 at it seems to work fine.  But 5.5 or 5.6 would be even better.

**Comment by rhukster** [comment] 2015-08-11 22:27
Also can you compare the CLI version of PHP to your Apache/webserver version:

```
$ php -v
```

and:

`info.php`
```
<? phpinfo();
```

Point your browser at `http://localhost/info.php`

**Comment by PSiAU** [comment] 2015-08-11 22:34
Both versions match: PHP 5.4.41-0+deb7u1
I also tried disabling Zend OPcache 7.0.5 just in case it could have contributed to the problem (trying everything at this stage) but no it didn't help either.

**Comment by rhukster** [comment] 2015-08-11 23:21
I'm running out of ideas! :)  Just to confirm:

1) you can install via admin and gpm
2) you can list via admin and gpm
3) you can uninstall via gpm, but not admin

That  correct?

**Comment by PSiAU** [comment] 2015-08-11 23:38
Yup! That about sums it up.
I really hope it's not just me doing something wrong, i'd feel like a right fool otherwise.

**Comment by w00fz** [comment] 2015-08-11 23:55
What makes this weird is that it looks like it's a stream issue, but you are able to list all plugins and themes which are using the same stream. Plus you can even delete via CLI and GPM.

Could you try editing the file `system/src/Grav/Common/Filesystem/Folder.php`, line `246` and make it:

```php
var_dump('target', $target, 'is_dir', is_dir($target)); die;
if (!is_dir($target)) {
```

Then post here what you get?

**Comment by PSiAU** [comment] 2015-08-12 02:03
This is the result:
string(6) "target" bool(false) string(6) "is_dir" bool(false)

**Comment by PSiAU** [comment] 2015-08-12 10:26
I just setup a completely new Debian 8 VM with the following components:
Apache 2.4
PHP 5.6 running as mod_php

The same thing is happening :(

**Comment by flaviocopes** [comment] 2015-08-12 12:48
Good news! Replicated on a shared hosting. I'll test directly there.

**Comment by PSiAU** [comment] 2015-08-12 13:41
Really glad to hear that! Thanks so much for keeping at it.

**Comment by flaviocopes** [comment] 2015-08-12 14:07
Fixed by 42e6d587d8569c28858d2a9da1e649857200fc88

**Comment by flaviocopes** [comment] 2015-08-12 14:10
Ok @PSiAU it was a simple fix in the end, once I got to the head of the problem! 

You can install the latest Grav source from https://github.com/getgrav/grav or just apply the fix https://github.com/getgrav/grav/commit/42e6d587d8569c28858d2a9da1e649857200fc88, or just wait for the next Grav update to contain the fix :)

Thanks for your patience in solving this!

**Closed by flaviocopes** 2015-08-12 14:10 UTC
Labels: more info needed, question

**Comment by PSiAU** [comment] 2015-08-12 14:12
no that YOU @flaviocopes  :)
I manually patched the file and can confirm it's fixed the problem.

**Comment by flaviocopes** [comment] 2015-08-12 14:13
:tada:
