### ISSUE TITLE
Can't click on any buttons in fullscreen

### ISSUE THREAD

**Issue by forteller** [getgrav/grav-plugin-admin#830] opened 2016-10-20 01:13 UTC
Hi. I'm on Grav 1.1.6. When I edit pages and turn on fullscreen mode on a page I can't click on any of the buttons, even the exit fullscreen mode button.

Thanks for all the hard work, guys!

**Comment by rhukster** [comment] 2016-10-20 04:14
I don't think this changed in the last release but have assumed to @w00fz as he would know best.

**Comment by flaviocopes** [comment] 2016-10-20 09:16
Can't reproduce with Chrome. Which browser are you using? Can you try Chrome if different?

Also, try using Incognito mode to disable any browser plugin that might interfere.

**Comment by forteller** [comment] 2016-10-22 10:17
Ok, I have no idea why, but now the buttons work, without me doing anything different. I'll let you know if it happens again. I'm on Firefox 49.

**Comment by w00fz** [comment] 2016-10-24 18:59
I'm closing the issue for now as I can't reproduce either.

Please feel free to reopen if it happens again, I'm suspecting it was just the JS cached on your browser.

**Closed by w00fz** 2016-10-24 18:59 UTC
