### ISSUE TITLE
Unable to install Nextgen Editor - Premium Plugin - GPM Error

### ISSUE THREAD

**Issue by bachurva** [getgrav/grav-plugin-admin#2175] opened 2021-09-01 06:51 UTC
I see this error while trying to install the Nextgen Editor - Premium Plugin.

"GPM not reachable. Please check your internet connection or check the GRAV site is reachable."

The internet connection is fine.

Can you indicate what may be causing this error?

Thanks
![Nextgen Editor Error](https://user-images.githubusercontent.com/44727728/131625295-90329e18-9341-4d95-aa83-913943945264.png)

**Comment by mahagr** [comment] 2021-09-01 07:01
GPM seems to be up, can you try again?

**Comment by bachurva** [comment] 2021-09-01 07:37
Still seeing the same error

**Comment by w00fz** [comment] 2021-09-02 19:09
Im closing this one as it's a duplicate of https://github.com/getgrav/grav-premium-issues/issues/144

**Closed by w00fz** 2021-09-02 19:09 UTC
