### ISSUE TITLE
Frontmatter in expert mode won't save

### ISSUE THREAD

**Issue by rcheetah** [getgrav/grav-plugin-admin#2047] opened 2021-01-28 21:54 UTC
When using the expert mode and editing the frontmatter, sometimes it just won't save. This is happening very often to me, but not always.

I could produce this bug with variables that aren't used anymore, when all third party plugins were deactivated, the default quark theme was loaded and the cache was cleared. So it should'nt be related with my setup (i hope).

I don't know which infos I can provide, so please ask for anything that helps resolving this bug. I'll attach a screencast of this bug. 

https://user-images.githubusercontent.com/15356984/106203512-c661aa00-61bb-11eb-8702-a270e6fcffc2.mp4

**Comment by mahagr** [comment] 2021-01-29 02:36
Duplicate of https://github.com/getgrav/grav/issues/3174

**Closed** 2021-01-29 02:36 UTC
Labels: 1.10, duplicate
