### ISSUE TITLE
Fieldtype datetime does not display datepicker after upgrade from v1.8.15 

### ISSUE THREAD

**Issue by grelle** [getgrav/grav-plugin-admin#1584] opened 2019-01-09 13:03 UTC
I run two grav-sites. One with admin-plugin v1.8.15 and one with the latest version.

In the latest version the field-type "datetime" does not produce a datepicker in Chrome.

**Comment by rhukster** [comment] 2019-01-09 17:34
Duplicate of: https://github.com/getgrav/grav-plugin-admin/issues/1581

Already fixed in develop branch.

**Closed by rhukster** 2019-01-09 17:34 UTC
Labels: duplicate
