### ISSUE TITLE
Last Modified dates aren't visible on Dashboard page

### ISSUE THREAD

**Issue by mcspronko** [getgrav/grav-plugin-admin#663] opened 2016-06-12 13:24 UTC
# Steps to Reproduce

1. Navigate to Grav Admin panel -> Configuration -> System
2. Change "Translations enabled" setting to "No"
3. Click "Save" button
4. Navigate to Dashboard page
5. Observe Last Modified dates.

**Actual Result**
Last Modified Placeholder is shown instead of date/time human readable text.
<img width="252" alt="screenshot 2016-06-12 14 17 28" src="https://cloud.githubusercontent.com/assets/3740515/15991357/a4380792-30a8-11e6-94ca-90c19f02406e.png">

** Expected Result **
Last Modified date should be shown.
<img width="236" alt="screenshot 2016-06-12 14 19 41" src="https://cloud.githubusercontent.com/assets/3740515/15991364/b9edd486-30a8-11e6-9ad4-848368ce38a1.png">

## Observations
The \Grav\Common\Language\Language::translate() method checks _$this->config->get('system.languages.translations', true)_ configuration setting. In case the setting is set to "true" the default language is pre-populated. It seems like default language should be moved out from if statement.

**Comment by flaviocopes** [comment] 2016-06-13 07:54
@mcspronko Grav 1.1 or Grav 1.0?

**Comment by flaviocopes** [comment] 2016-06-13 07:55
@mcspronko I ask because i cannot reproduce it in Grav 1.1, and Admin 1.1

**Comment by mcspronko** [comment] 2016-06-14 22:50
Hi @flaviocopes 

I am using Admin 1.0.10

**Comment by flaviocopes** [comment] 2016-06-15 06:36
Ok looks to be already solved then in 1.1 RC.

Closing now, if you get a chance to try it, report back if you got the same problem.

**Closed by flaviocopes** 2016-06-15 06:36 UTC
Labels: bug, cannot recreate
