### ISSUE TITLE
Error while trying to download

### ISSUE THREAD

**Issue by ZteamDL** [getgrav/grav-plugin-admin#1861] opened 2020-03-24 01:26 UTC
![fefsf](https://user-images.githubusercontent.com/59402172/77378660-dd06cb80-6d76-11ea-877f-c11b5d3af8b4.PNG)

Is there any way to fix that?

**Comment by rhukster** [comment] 2020-03-24 02:25
try changing the `gpm.method` option in system.yaml.  It tries curl first, then fopen, but you can force one or the other.  Try forcing `fopen` and see if that works.

**Comment by TomPecs** [comment] 2020-03-24 19:42
same to me :\ any plugin // have a feeling host/php settings problem limitation....

**Comment by TomPecs** [comment] 2020-03-24 19:42
![image](https://user-images.githubusercontent.com/59783091/77469847-9d3bf480-6e07-11ea-95c0-057af6f0d39e.png)

**Comment by rhukster** [comment] 2020-03-24 19:59
If that's working for you then that means there's a problem with Curl on your server machine.

**Comment by rhukster** [comment] 2020-04-01 17:36
duplicate of https://github.com/getgrav/grav-plugin-admin/issues/1847

**Closed by rhukster** 2020-04-01 17:36 UTC
Labels: duplicate
