### ISSUE TITLE
custom scheduler jobs cannot be removed

### ISSUE THREAD

**Issue by beijersb** [getgrav/grav-plugin-admin#1872] opened 2020-04-24 06:13 UTC
In the admin page under Tools en tab scheduler:
When one creates a custom job, you cannot remove it any any-more. When clicking the trashcan icon the job is removed from the ui, but clicking save simply restores the job.

Another weird thing: try adding a `[` as first character of the ID, then click "Save". After that the job still exits, and the `[` is replaced with: `&#x5B;` Now try assigning an new ID. This won't work any more, you can't get rid of the `&#x5B;` !  

BTW manually removing the custom job from: `usr/config/scheduler.yaml` works fine. In this file the `[` still shows up. So this workaround mitigates the problem to a minor inconvenience.

**Comment by mahagr** [comment] 2020-04-24 09:59
The last item cannot be removed because the data gets merged with the existing file. I don't think this is a new bug.

I cannot reproduce the second issue, it won't let me save.

**Comment by mahagr** [comment] 2021-02-09 18:37
Same as https://github.com/getgrav/grav-plugin-admin/issues/2056

**Closed by mahagr** 2021-02-09 18:37 UTC
Labels: bug
