### ISSUE TITLE
Error while trying to download (code: 0): https://getgrav.org/download/plugins/simplesearch/1.14.2 Message: URL using bad/illegal format or missing URL malformed

### ISSUE THREAD

**Issue by Virelin** [getgrav/grav-plugin-admin#1864] opened 2020-04-01 11:49 UTC
This happens with all plugins I like to install from inside the admin

**Comment by rhukster** [comment] 2020-04-01 17:33
duplicate of this: https://github.com/getgrav/grav-plugin-admin/issues/1863

**Closed by rhukster** 2020-04-01 17:33 UTC
Labels: duplicate
