### ISSUE TITLE
Pages list not loading in admin panel

### ISSUE THREAD

**Issue by philmacnevin** [getgrav/grav-plugin-admin#1858] opened 2020-03-20 19:00 UTC
Hey! I updated to the new Admin panel v1.10.0-rc.8 (and Flex Objects v1.0.0-rc.8), and now the page list won't load in my admin panel when I go to edit pages. All I get is the spinning loading circle, but nothing loads.

When I go to view page source, I get these errors which I think has to do with Flex Objects...

<img width="363" alt="Screen Shot 2020-03-20 at 3 59 01 PM" src="https://user-images.githubusercontent.com/6206951/77197398-e0266100-6ac3-11ea-8b69-8de50346d95b.png">

**Comment by rhukster** [comment] 2020-03-20 19:59
Duplicate of #1857

**Closed by rhukster** 2020-03-20 19:59 UTC
Labels: duplicate
