### ISSUE TITLE
Switcher of languages is not displayed correctly

### ISSUE THREAD

**Issue by desvu** [getgrav/grav-plugin-admin#379] opened 2016-01-04 18:00 UTC
![s](https://cloud.githubusercontent.com/assets/16544732/12096305/9f17ae44-b33e-11e5-9322-0e694850354d.png)

Google Chrome 47

**Comment by mahagr** [comment] 2020-12-01 19:48
Should be fixed, cannot reproduce.

**Closed by mahagr** 2020-12-01 19:48 UTC
Labels: ui
