### ISSUE TITLE
Creating pages with a field type of 'file' breaks on save

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-plugin-admin#2046] opened 2021-01-28 18:06 UTC
I now see this error when trying to save:
Save Failed: Cannot set nested property header introimage imagename.jpg on non-array value

Grav v1.7.3 - Admin v1.10.2 Flex Objects 1.0.1

Disabling Pages (Admin) in the flex objects plugin solved my issue.

**Comment by mahagr** [comment] 2021-02-01 14:01
I need an example of how to reproduce this error. Blueprint file and some walkthrough on a clean install would do it.

**Comment by mahagr** [comment] 2021-02-01 14:04
Duplicate of #1967

**Comment by mahagr** [comment] 2021-02-01 14:20
Fixed in https://github.com/getgrav/grav/issues/3191

**Closed by mahagr** 2021-02-01 14:20 UTC
Labels: 1.10, duplicate
