### ISSUE TITLE
Having to save settings before changing tab...

### ISSUE THREAD

**Issue by MATsxm** [getgrav/grav-plugin-admin#302] opened 2015-11-26 15:54 UTC
Bonjour,
Not a bug but...

**How to reproduce**
Go to: Configuration then change for example the 'Site Title' then click the 'System' tab before saving then go back to the 'Site' tab again.

**What happens**
the new setting for the 'Site Title' disappeared and the former appears.

**expected behaviour**
The new value for the field stays even after switching from tabs to tabs without having to 'Save' before the switch.

I hope I'm clear enough :wink: 
Thanks and Great Job!!!

**Comment by flaviocopes** [comment] 2015-11-26 16:39
The problem is that tabs are not javascript-based, but when switching tabs you go to a completely different page, so the old value cannot be restored unless saved. We could ask for a confirmation when switching tabs when a value has been changed, but not yet saved.

**Comment by MAT978** [comment] 2015-11-26 18:26
tbh, I don't think it is a real problem, we just have to get used.
Having an 'Alert' won't be "user friendly" anyway then feel free to close this.

Thanks

**Closed** 2015-11-30 03:04 UTC
Labels: by design
