### ISSUE TITLE
GRAV Admin Cache Issue

### ISSUE THREAD

**Issue by embieone** [getgrav/grav-plugin-admin#766] opened 2016-09-07 12:33 UTC
In my multi language GRAV site I recently noticed a cache issue.

When I change the language in page overview I get the message `Successfully switched language` and anything seems alright.

But when I edit a page and go back to the page overview, the original language appears again instead of the recently selected language, furthermore I get the message `invalid security token`.

Only if I force a reload without cache the selected language appears correctly and the message disappears.

On the next language change the issue occurs again.

How can I solve this issue ?

Thanks in advance

**Comment by flaviocopes** [comment] 2016-09-07 12:46
Which browser are you using? Also, latest Grav + Admin?

**Comment by embieone** [comment] 2016-09-07 13:08
I tested it in Firefox ( 48.0.2 ) and Chrome ( 52 ) and MS rim ( 25 ) . Initially I had Grav v1.1.1 and v1.1.2 Admin installed, then I thought an update may fix the problem. So I upgraded to the latest version, but nothing changed except in the latest version the invalid security token message appeared.

**Comment by flaviocopes** [comment] 2016-09-08 11:54
Cannot reproduce. Can you check if the same happens with our MultiLang Skeleton which you can find here https://getgrav.org/downloads/skeletons ?

**Comment by flaviocopes** [comment] 2016-09-08 11:55
"Invalid security token" is only happening when saving pages, or also with configuration / plugins settings too?

**Comment by embieone** [comment] 2016-09-08 14:16
"Invalid security token" is happening on every action which causes a page reload e.g. switching from pages to configuration.

Sure I'll check your MultiLang Skeleton. 

For test purpose, to be sure that it's not the server who causes the issue,  I ported the Project to my private server. If it helps I can send you the login information.

**Comment by embieone** [comment] 2016-09-08 14:38
I've tested your MultiLang Skeleton. 
It shows almost the same behavior as my Project except the "Invalid security token" message.

**Comment by embieone** [comment] 2016-09-08 15:03
After updating the project to the latest GRAV(1.1.4) and Admin(1.2.1) the "Invalid security token" message is gone, but the cache issue still exists.

**Comment by flaviocopes** [comment] 2016-09-09 11:50
Is the page cache in the System settings enabled? Try disabling, same issue?

**Comment by embieone** [comment] 2016-09-09 12:42
Yes, page cache was enabled. Same issue with disabled cache.

**Comment by mahagr** [comment] 2020-12-01 20:09
This issue should be fixed at least in Admin 1.10.

**Closed by mahagr** 2020-12-01 20:09 UTC
Labels: evaluating
