### ISSUE TITLE
Labels in backup managers displayed as constants ?

### ISSUE THREAD

**Issue by netagence** [getgrav/grav-plugin-admin#1763] opened 2019-10-13 13:40 UTC
Hello,
I seem to have labels as

GRAV.NICETIME.MIN_PLURAL
Newest Backup
GRAV.NICETIME.MIN_PLURAL
Oldest Backup

at /admin/tools/backups

Best regards.

**Comment by rhukster** [comment] 2019-10-13 15:52
Have you upgraded grav to latest version?

**Comment by netagence** [comment] 2019-10-13 15:58
Hi,
Yes I am on

*# v1.6.16
## 09/19/2019
*
but not sure if it occured after the upgrade.

**Comment by rhukster** [comment] 2019-10-25 03:47
Are you running the admin in a non-english language?  I can't replicate this with the default 'english' language.

**Comment by ltGuillaume** [comment] 2019-11-13 23:32
I can confirm this behavior, even with English.
Also, see https://github.com/getgrav/grav-plugin-admin/issues/1678

Running v1.6.17 (11/06/2019)

**Comment by AnaelMobilia** [comment] 2019-12-28 15:26
Hello,

I just created a new backup on my grav installation.

The graphical interface now have this strange glitch :
![image](https://user-images.githubusercontent.com/6187125/71545689-844daf80-298e-11ea-9d8c-b7c0938b8ced.png)

Grav version : Grav v1.6.19 - Admin v1.9.12

**Comment by rhukster** [comment] 2019-12-28 23:20
What plugins do you have installed? I can’t replicate this at all.

**Comment by AnaelMobilia** [comment] 2019-12-29 20:05
Hello,

Installed plugins :
![image](https://user-images.githubusercontent.com/6187125/71562018-7a0ade80-2a7e-11ea-8f6f-525f56e0a9ff.png)

Hosted on a shared web hosting on OVH (PHP 7.3.12)

Regards,
Anael

**Comment by ltGuillaume** [comment] 2019-12-29 21:20
![image](https://user-images.githubusercontent.com/4777345/71563006-513c1680-2a89-11ea-98b3-27764608f30a.png)
Grav v1.6.19

**Comment by AnaelMobilia** [comment] 2020-12-17 23:21
Still present on Grav v1.6.31 - Admin v1.9.19 (same module as previous, full up-to-date).

As a debug, i notice that the [function nicetimeFunc($date, $long_strings = true, $show_tense = true)](https://github.com/getgrav/grav/blob/master/system/src/Grav/Common/Twig/TwigExtension.php#L494) is called with params : ("Sat, 28 Dec 2019 16:22:04 +0100", false, false)

On the twig template file [newest_date](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/partials/tools-backups.html.twig#L7) is correct "Sat, 28 Dec 2019 16:22:04 +0100 ". But the [newest_backup](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/partials/tools-backups.html.twig#L8) is already a bad string  "12 GRAV.NICETIME.MO_PLURAL "

The [function adminNicetimeFilter($date, $long_strings = true)](https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/Twig/AdminTwigExtension.php#L113) is called for displaying "Latest Page Updates" on Dashboard but not on Tools.

On the [themes/grav/templates/partials/dashboard-pages.html.twig](https://github.com/getgrav/grav-plugin-admin/blob/4c37461caa3d4b6d8cd9b90529de5725e895ab79/themes/grav/templates/partials/dashboard-pages.html.twig#L12), filter adminNicetime is used.
On the [themes/grav/templates/partials/tools-backups.html.twig](https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/partials/tools-backups.html.twig#L8), filter nicetime is used.

Based on this, I made the related PR.
Regards,
Anael

**Comment by rhukster** [comment] 2021-01-24 01:55
For those finding this, make sure you don't have "Translations" disabled in the "Languages" section of the "System" configuration

**Comment by ltGuillaume** [comment] 2021-01-24 02:01
Ouch that must have been the case, because after the upgrade to 1.7, _all_ strings were shown as the key names instead of the translated values.

**Comment by rhukster** [comment] 2021-01-24 02:11
Yes that setting was actually broken in 1.6, it was not fully disabling translations.  That is fixed in 1.7 but now it's catching people off-guard that had toggled that and not toggled it back because they saw no differences.

**Comment by ltGuillaume** [comment] 2021-01-24 02:16
Makes total sense now. Thanks!

**Comment by AnaelMobilia** [comment] 2021-01-24 12:02
Nice catch (Cf #2038) !
I close #2003 in consequences.

Regards

**Closed** 2021-01-26 09:29 UTC
Labels: cannot recreate
