### ISSUE TITLE
Erroneous renaming while Save As in multilingual site

### ISSUE THREAD

**Issue by zverok** [getgrav/grav-plugin-admin#475] opened 2016-04-04 07:41 UTC
Consider the situation:

1. We had not-multilingual site with pages named, say `user/pages/05.news/newsitem.md`
2. We add multilinguality
3. We try to save language versions of page (via clicking "Save as English" in Admin)
4. Now we have `user/pages/05.news/newsi.en.md` (note "newsi" instead of "newsitem")

The problem seems to be [here](https://github.com/getgrav/grav-plugin-admin/blob/develop/classes/controller.php#L1740) -- the part of name of length `strlen('.' . $language . '.md')` is mechanically dropped. When page previously had no ".xx" suffix, dropped part is a part of page  name.

**Comment by zverok** [comment] 2016-04-04 07:49
As far as I understand, all that block of code is just a set of bugs, masking each other.
Right (or "working for me") version:

```php
            $filename = substr($obj->name(), 0, -(strlen('.md'))); # was: -(strlen('.' . $language . '.md')

            if (substr($filename, -3, 1) == '.') {
                if (substr($filename, -2) != substr($language, 0, 2)) { # was: ==
                    $filename = str_replace(substr($filename, -2), $language, $filename);
                }
            } elseif (substr($filename, -6, 1) == '.') {
                if (substr($filename, -5) != substr($language, 0, 5)) { # was: ==
                    $filename = str_replace(substr($filename, -5), $language, $filename);
                }
            } else {
                $filename .= '.' . $language;
            }
```

Either I missing something, or I'm pretty surprised

**Comment by flaviocopes** [comment] 2016-04-04 09:13
Mmm strange, cannot reproduce such problem. 
To me the page is correctly saved as `newsitem.en.md`.

**Comment by zverok** [comment] 2016-04-04 09:19
Wow. That's pretty strange. I did a thorough testing and checking before reporting a bug. And just by reading the code it can be seen, I think:
```php
// $obj->name() == 'newsitem.md'
// $language == 'en'

$filename = substr($obj->name(), 0, -(strlen('.' . $language . '.md')));
// how this line can produce anything other than "newsi"?

// of this branches, last else will perform:
if (substr($filename, -3, 1) == '.') {
    if (substr($filename, -2) == substr($language, 0, 2)) {
        $filename = str_replace(substr($filename, -2), $language, $filename);
    }
} elseif (substr($filename, -6, 1) == '.') {
    if (substr($filename, -5) == substr($language, 0, 5)) {
        $filename = str_replace(substr($filename, -5), $language, $filename);
    }
} else {
    $filename .= '.' . $language; // and the final result is "newsi.en"
}
```

**Comment by rhukster** [comment] 2016-04-04 15:03
i'm going to try testing this today also.

**Comment by flaviocopes** [comment] 2016-06-07 21:08
Cannot replicate as well

**Comment by flaviocopes** [comment] 2016-06-16 15:40
@zverok closing this as I cannot replicate. Try with the latest Grav 1.1 RC and comment back if you still have the issue.

**Closed by flaviocopes** 2016-06-16 15:40 UTC
Labels: bug
