### ISSUE TITLE
Visibility option in 'Add page' dialogue box doesn't carry over to page edit. 

### ISSUE THREAD

**Issue by asteroidice** [getgrav/grav-plugin-admin#681] opened 2016-07-01 23:42 UTC
I'm not sure if this is a specific issue with my new installation or if it's a bug that actually exists on the repo. Regardless when I add a page and select to have its visibility status set to 'yes' the frontmatter section only shows
```
title: 'Test page'
```
but should it display?
```
title: 'Test page'
visible: true
```

Love the grav and the grav admin plugin BTW.

**Comment by flaviocopes** [comment] 2016-07-04 12:57
Are you using Grav 1.1 or 1.0?

Looks like it's not "persisted" to the second page, the one where the page is actually saved.
I did a test on Grav 1.1 and to me it's actually worse, marking it as `visible: false`.

Marking as a bug.

**Comment by flaviocopes** [comment] 2016-07-04 13:09
@w00fz @rhukster I never thought about that but I have a question now, does it make sense to have this setting in the "Create page" modal, or it can be removed? Is it such a common setting that needs to be in that modal?

**Comment by rhukster** [comment] 2016-07-04 13:50
I think it's quite important to have in the modal. Some pages you clearly want to have visible and others like blog posts you want non visible (in menu). I thought we had the feature where the modal remembers the previous settings but have not tested since the JS revamp.

Thanks,

--
Andy Miller
Sent with Airmail

**Comment by flaviocopes** [comment] 2016-07-04 14:31
Yes, makes sense. Checking the problem

**Comment by flaviocopes** [comment] 2016-07-04 16:06
Actually, reading the code it's not a bug. If set to yes, the page has an ordering set, which automatically enables visibility on it. Only explicitly leaving it to false is persisted to the page header. Might be strange, and can be changed if it does not make sense, but the end result is the same as having `visible: true` in the page header.

I tricked myself with a test override I had set in my theme for `header.visible` which forced it to false, hence my issue above.

**Comment by asteroidice** [comment] 2016-07-05 02:08
Oh I'm actually using version 1.0.10.  If it works in the newer version than its not a problem. And I guess I could override it in the theme's template. I was just thinking that of the three options for visibility (auto, yes and no) 'yes' would force the page to be visible and it would do it by setting the visibility option to true. If its working as intended than its fine.

**Comment by flaviocopes** [comment] 2016-07-06 08:32
Yes, it's setting it, but in a different way - not explicitly, but by giving the page folder name an ordering number, which in turn makes it visible - I think it works the same way in 1.0.10, as that part has not changed.

**Closed by flaviocopes** 2016-07-06 08:32 UTC
Labels: bug
