### ISSUE TITLE
Activating a theme throws "Data type 'system' doesn't exist!" error

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-admin#635] opened 2016-06-02 04:33 UTC
Probably related to this fix I made in Core: https://github.com/getgrav/grav/commit/4fbf4329fdf53689943fe1ccaf3f581c01f9e65c

**Comment by Sogl** [comment] 2016-06-02 05:50
:+1:

**Comment by flaviocopes** [comment] 2016-06-02 09:46
The cause of the problem is not that core change, but this Admin commit instead https://github.com/getgrav/grav-plugin-admin/commit/8cd0279b018e40d1e3092fcc6821e8655e0c29f7, the merged `feature/upload-improvements` branch

**Comment by flaviocopes** [comment] 2016-06-02 09:56
Some old data types were removed from `Admin::data()`, and were not found.

**Closed** 2016-06-02 09:56 UTC
Labels: bug
