### ISSUE TITLE
Content in Editor Not Appearing at First

### ISSUE THREAD

**Issue by simmonsr** [getgrav/grav-plugin-admin#1052] opened 2017-04-05 21:47 UTC
If you start at Edit Page > Options tab, then refresh browser page, then move to Content tab, you should see that the content in editor is missing:

![screen_shot_2017-04-05_at_3 54 55_pm_720](https://cloud.githubusercontent.com/assets/5002814/24728429/64cd115e-1a1f-11e7-819b-248217f05cf7.jpg)

Once I click on the editor box though it appears:

![screen_shot_2017-04-05_at_3 56 05_pm_720](https://cloud.githubusercontent.com/assets/5002814/24728455/7c6052f4-1a1f-11e7-863b-faee31646a51.jpg)

I can replicate in FireFox and Chrome.

**Comment by rhukster** [comment] 2017-04-05 23:54
Never run into this! But probably a JS init thing.  assigning to the master...

**Comment by axel-rank** [comment] 2017-04-06 07:53
Yes, I can confirm this happening since Grav 1.2, Admin 1.3.1. Using Firefox.

**Comment by jeremycherfas** [comment] 2017-04-09 09:24
I can confirm this is happening also in Safari 10.0.3 since the recent updates.

**Comment by w00fz** [comment] 2017-04-10 03:56
This is now fixed

**Closed** 2017-04-10 03:56 UTC
Labels: bug
