### ISSUE TITLE
Parent option it's not returning the correct value

### ISSUE THREAD

**Issue by blurkness** [getgrav/grav-plugin-admin#406] opened 2016-01-23 16:50 UTC
When you select the parent page and save, the option value return to - Root -
It's working in production but everytime i have to choose the correct parent before save the page.

ps: parent and the page are both Page Type

**Comment by flaviocopes** [comment] 2016-01-24 18:52
Cannot replicate. 

Which browser are you using?
Which page type is the page?
Is the folder actually moved?

**Comment by blurkness** [comment] 2016-01-24 20:29
Browser: Google Chrome (48.0)

**Root page config**
* type: page
* folder name: 99-about
* parent: root
* slug: about
* default child type: page
* visible: true

**Child page config**
* type: page
* folder name: blurkness
* parent: about

I just changed the root folder name using the Admin Panel to *99-about*.

**Comment by flaviocopes** [comment] 2016-01-25 08:33
The root page is the home page?

**Comment by blurkness** [comment] 2016-01-25 09:11
nope, just a page... i'll try to recreate with a clean install.

**Comment by blurkness** [comment] 2016-01-26 14:00
The same issue happen wIth the clean install. Try to recreate with two pages using **default type**.

**Comment by flaviocopes** [comment] 2016-01-26 14:17
Still not able to replicate, with the same browser. Maybe you can make a quick screencast to show the exact steps, also showing the pages / folders structure? You can PM it to me in Gitter

**Comment by flaviocopes** [comment] 2016-01-26 15:46
Replicated with 1.0.8, but already fixed in the Grav repo. 
Was caused by the parent page having a `slug` set.

**Closed by flaviocopes** 2016-01-26 15:46 UTC
Labels: cannot recreate
