### ISSUE TITLE
Clicking Configuration button throws an error 

### ISSUE THREAD

**Issue by acte28** [getgrav/grav-plugin-admin#2166] opened 2021-07-21 14:22 UTC
Encountered this error when recently having set up Grav. When I click 'Configuration' at the top right under the Pages Window I get the following error.

TypeError
Return value of Grav\Framework\Flex\FlexDirectory::loadDirectoryConfig() must be of the type array, null returned

--

/var/www/html/grav/system/src/Grav/Framework/Flex/FlexDirectory.php
    }
 
    /**
     * @param string $name
     * @return array
     * @internal
     */
    public function loadDirectoryConfig(string $name): array
    {
        $grav = Grav::instance();
 
        /** @var UniformResourceLocator $locator */
        $locator = $grav['locator'];
        $uri = $this->getDirectoryConfigUri($name);
 
        // If configuration is found in main configuration, use it.
        if (str_starts_with($uri, 'config://')) {
            $path = strtr(substr($uri, 9,  -5), '/', '.');
 
            return $grav['config']->get($path);
        }
 
        // Load the configuration file.
        $filename = $locator->findResource($uri, true);
        if ($filename === false) {
            return [];
        }
 
        $file = YamlFile::instance($filename);
 
        return $file->content();
    }
 
    /**
     * @param string|null $name
     * @return string
     */
    public function getDirectoryConfigUri(string $name = null): string
    {
        $name = $name ?: $this->getFlexType();
Arguments
"Return value of Grav\Framework\Flex\FlexDirectory::loadDirectoryConfig() must be of the type array, null returned"

**Comment by acte28** [comment] 2021-07-21 15:05
This error occurs on: Grav v1.7.18 - Admin v1.10.18 

Tried a similar instance using Grav v1.7.17 - Admin v1.10.17 and the Configuration button is accessible

**Comment by mahagr** [comment] 2021-07-22 14:08
Duplicate of https://github.com/getgrav/grav/issues/3409

**Closed by mahagr** 2021-07-22 14:08 UTC
Labels: duplicate
