### ISSUE TITLE
Grav 1.7 RC.6 Flex Pages UI search filter interface issue

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-admin#1830] opened 2020-02-13 21:40 UTC
The new search/filter feature for Grav Flex pages is fantastic! I've been trying it out, and notice that the interface unexpectedly partially scrolls up when you Apply Filters, as shown below:

![2020-02-13_13-31-24 (1)](https://user-images.githubusercontent.com/1812771/74480583-0b36e880-4e66-11ea-8ddf-1b55de64f3ad.gif)

I'd tend to expect that either the search/filter panel disappears and the filtered results are fully shown (preferred )OR the panel remains exactly in the same place for manual closing.

Please let me know if any additional info/testing is helpful.

Thanks very much,
Paul

**Comment by mahagr** [comment] 2020-02-13 22:51
@w00fz Can you take a look?

**Comment by w00fz** [comment] 2020-02-13 23:09
@paulhibbitts from what I’m seeing from your gif , that seems to be happening because when you start off filtering, the height of the page is greater than the height of the page after filtering. That causes the page to shift automatically to adjust for compensating to the shortening of the new  height.

Try filtering by published, you’ll probably see the shifting doesn’t happen anymore

**Comment by paulhibbitts** [comment] 2020-02-13 23:09
BTW, if it helps for testing purposes you can download the above skeleton shown at https://1drv.ms/u/s!Aoj9Cstt0NJ0kt4VMZlY6H_Z7yLAnA?e=PZQ1Ld

**Comment by paulhibbitts** [comment] 2020-02-13 23:13
Thanks for looking @w00fz , but that also seems to have the same issue:
![2020-02-13_15-11-16 (1)](https://user-images.githubusercontent.com/1812771/74487012-44c22080-4e73-11ea-96eb-65e1badf3826.gif)

You can download the skeleton shown above at https://1drv.ms/u/s!Aoj9Cstt0NJ0kt4VMZlY6H_Z7yLAnA?e=PZQ1Ld

What do you think of closing the filters panel once "Apply Filters" is tapped to then fully show the updated page list for navigation etc?

**Comment by w00fz** [comment] 2020-03-06 18:32
Fixed in trilbymedia/grav-plugin-flex-objects@8d9d3aaadcc4b3f127b2a8fda20a20d7349a5c13 .

This was an odd behavior I had to work around caused by the custom gemini scrollbars that we use throughout the whole admin which are not always so friendly.

Should be all good now, filters remain open but nothing jumps around causing dizziness.

**Closed by w00fz** 2020-03-06 18:32 UTC
Labels: ui

**Comment by paulhibbitts** [comment] 2020-03-06 18:39
Thanks very much @w00fz ! Looking forward to trying this out🙂
